<!DOCTYPE html>
<html lang="en"><head>
<script src="pres glm2_files/libs/clipboard/clipboard.min.js"></script>
<script src="pres glm2_files/libs/quarto-html/tabby.min.js"></script>
<script src="pres glm2_files/libs/quarto-html/popper.min.js"></script>
<script src="pres glm2_files/libs/quarto-html/tippy.umd.min.js"></script>
<link href="pres glm2_files/libs/quarto-html/tippy.css" rel="stylesheet">
<link href="pres glm2_files/libs/quarto-html/light-border.css" rel="stylesheet">
<link href="pres glm2_files/libs/quarto-html/quarto-syntax-highlighting-29e2c20b02301cfff04dc8050bf30c7e.css" rel="stylesheet" id="quarto-text-highlighting-styles"><meta charset="utf-8">
  <meta name="generator" content="quarto-1.6.37">

  <title>Generalized Linear Models</title>
  <meta name="apple-mobile-web-app-capable" content="yes">
  <meta name="apple-mobile-web-app-status-bar-style" content="black-translucent">
  <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no, minimal-ui">
  <link rel="stylesheet" href="pres glm2_files/libs/revealjs/dist/reset.css">
  <link rel="stylesheet" href="pres glm2_files/libs/revealjs/dist/reveal.css">
  <style>
    code{white-space: pre-wrap;}
    span.smallcaps{font-variant: small-caps;}
    div.columns{display: flex; gap: min(4vw, 1.5em);}
    div.column{flex: auto; overflow-x: auto;}
    div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
    ul.task-list{list-style: none;}
    ul.task-list li input[type="checkbox"] {
      width: 0.8em;
      margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
      vertical-align: middle;
    }
    /* CSS for syntax highlighting */
    pre > code.sourceCode { white-space: pre; position: relative; }
    pre > code.sourceCode > span { line-height: 1.25; }
    pre > code.sourceCode > span:empty { height: 1.2em; }
    .sourceCode { overflow: visible; }
    code.sourceCode > span { color: inherit; text-decoration: inherit; }
    div.sourceCode { margin: 1em 0; }
    pre.sourceCode { margin: 0; }
    @media screen {
    div.sourceCode { overflow: auto; }
    }
    @media print {
    pre > code.sourceCode { white-space: pre-wrap; }
    pre > code.sourceCode > span { display: inline-block; text-indent: -5em; padding-left: 5em; }
    }
    pre.numberSource code
      { counter-reset: source-line 0; }
    pre.numberSource code > span
      { position: relative; left: -4em; counter-increment: source-line; }
    pre.numberSource code > span > a:first-child::before
      { content: counter(source-line);
        position: relative; left: -1em; text-align: right; vertical-align: baseline;
        border: none; display: inline-block;
        -webkit-touch-callout: none; -webkit-user-select: none;
        -khtml-user-select: none; -moz-user-select: none;
        -ms-user-select: none; user-select: none;
        padding: 0 4px; width: 4em;
        color: #aaaaaa;
      }
    pre.numberSource { margin-left: 3em; border-left: 1px solid #aaaaaa;  padding-left: 4px; }
    div.sourceCode
      { color: #003b4f; background-color: #f1f3f5; }
    @media screen {
    pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
    }
    code span { color: #003b4f; } /* Normal */
    code span.al { color: #ad0000; } /* Alert */
    code span.an { color: #5e5e5e; } /* Annotation */
    code span.at { color: #657422; } /* Attribute */
    code span.bn { color: #ad0000; } /* BaseN */
    code span.bu { } /* BuiltIn */
    code span.cf { color: #003b4f; font-weight: bold; } /* ControlFlow */
    code span.ch { color: #20794d; } /* Char */
    code span.cn { color: #8f5902; } /* Constant */
    code span.co { color: #5e5e5e; } /* Comment */
    code span.cv { color: #5e5e5e; font-style: italic; } /* CommentVar */
    code span.do { color: #5e5e5e; font-style: italic; } /* Documentation */
    code span.dt { color: #ad0000; } /* DataType */
    code span.dv { color: #ad0000; } /* DecVal */
    code span.er { color: #ad0000; } /* Error */
    code span.ex { } /* Extension */
    code span.fl { color: #ad0000; } /* Float */
    code span.fu { color: #4758ab; } /* Function */
    code span.im { color: #00769e; } /* Import */
    code span.in { color: #5e5e5e; } /* Information */
    code span.kw { color: #003b4f; font-weight: bold; } /* Keyword */
    code span.op { color: #5e5e5e; } /* Operator */
    code span.ot { color: #003b4f; } /* Other */
    code span.pp { color: #ad0000; } /* Preprocessor */
    code span.sc { color: #5e5e5e; } /* SpecialChar */
    code span.ss { color: #20794d; } /* SpecialString */
    code span.st { color: #20794d; } /* String */
    code span.va { color: #111111; } /* Variable */
    code span.vs { color: #20794d; } /* VerbatimString */
    code span.wa { color: #5e5e5e; font-style: italic; } /* Warning */
  </style>
  <link rel="stylesheet" href="pres glm2_files/libs/revealjs/dist/theme/quarto-bbe7401fe57d4b791b917637bb662036.css">
  <link href="pres glm2_files/libs/revealjs/plugin/quarto-line-highlight/line-highlight.css" rel="stylesheet">
  <link href="pres glm2_files/libs/revealjs/plugin/reveal-menu/menu.css" rel="stylesheet">
  <link href="pres glm2_files/libs/revealjs/plugin/reveal-menu/quarto-menu.css" rel="stylesheet">
  <link href="pres glm2_files/libs/revealjs/plugin/reveal-chalkboard/font-awesome/css/all.css" rel="stylesheet">
  <link href="pres glm2_files/libs/revealjs/plugin/reveal-chalkboard/style.css" rel="stylesheet">
  <link href="pres glm2_files/libs/revealjs/plugin/quarto-support/footer.css" rel="stylesheet">
  <style type="text/css">
    .reveal div.sourceCode {
      margin: 0;
      overflow: auto;
    }
    .reveal div.hanging-indent {
      margin-left: 1em;
      text-indent: -1em;
    }
    .reveal .slide:not(.center) {
      height: 100%;
      overflow-y: auto;
    }
    .reveal .slide.scrollable {
      overflow-y: auto;
    }
    .reveal .footnotes {
      height: 100%;
      overflow-y: auto;
    }
    .reveal .slide .absolute {
      position: absolute;
      display: block;
    }
    .reveal .footnotes ol {
      counter-reset: ol;
      list-style-type: none; 
      margin-left: 0;
    }
    .reveal .footnotes ol li:before {
      counter-increment: ol;
      content: counter(ol) ". "; 
    }
    .reveal .footnotes ol li > p:first-child {
      display: inline-block;
    }
    .reveal .slide ul,
    .reveal .slide ol {
      margin-bottom: 0.5em;
    }
    .reveal .slide ul li,
    .reveal .slide ol li {
      margin-top: 0.4em;
      margin-bottom: 0.2em;
    }
    .reveal .slide ul[role="tablist"] li {
      margin-bottom: 0;
    }
    .reveal .slide ul li > *:first-child,
    .reveal .slide ol li > *:first-child {
      margin-block-start: 0;
    }
    .reveal .slide ul li > *:last-child,
    .reveal .slide ol li > *:last-child {
      margin-block-end: 0;
    }
    .reveal .slide .columns:nth-child(3) {
      margin-block-start: 0.8em;
    }
    .reveal blockquote {
      box-shadow: none;
    }
    .reveal .tippy-content>* {
      margin-top: 0.2em;
      margin-bottom: 0.7em;
    }
    .reveal .tippy-content>*:last-child {
      margin-bottom: 0.2em;
    }
    .reveal .slide > img.stretch.quarto-figure-center,
    .reveal .slide > img.r-stretch.quarto-figure-center {
      display: block;
      margin-left: auto;
      margin-right: auto; 
    }
    .reveal .slide > img.stretch.quarto-figure-left,
    .reveal .slide > img.r-stretch.quarto-figure-left  {
      display: block;
      margin-left: 0;
      margin-right: auto; 
    }
    .reveal .slide > img.stretch.quarto-figure-right,
    .reveal .slide > img.r-stretch.quarto-figure-right  {
      display: block;
      margin-left: auto;
      margin-right: 0; 
    }
  </style>
</head>
<body class="quarto-light">
  <div class="reveal">
    <div class="slides">

<section id="title-slide" class="quarto-title-block center">
  <h1 class="title">Generalized Linear Models</h1>

<div class="quarto-title-authors">
</div>

</section>
<section id="this-lecture" class="slide level2">
<h2>This lecture</h2>
<p>You can access it from: <a href="https://rpubs.com/amolina/presentation2" class="uri">https://rpubs.com/amolina/presentation2</a></p>
<p>Review of linear models</p>
<p>Assumptions of glm’s</p>
<p>Mixed effects models</p>
</section>
<section id="how-to-interpret-glms-outputs" class="slide level2">
<h2>How to interpret GLM’s outputs?</h2>
<ul>
<li class="fragment">Let’s remember that linear models, and glm’s have a “linear” deterministic component</li>
</ul>

<img data-src="pres-glm2_files/figure-revealjs/unnamed-chunk-1-1.png" width="960" class="r-stretch"></section>
<section id="how-to-interpret-glms-outputs-1" class="slide level2">
<h2>How to interpret GLM’s outputs?</h2>
<ul>
<li class="fragment"><p>Let’s remember that linear models, and glm’s have a “linear” deterministic component</p></li>
<li class="fragment"><p>In linear models: <span class="math inline">\(\mu_i = \beta_0 + \beta_1x_{1,i} ...\)</span> (which means, the expected value of y )</p></li>
<li class="fragment"><p>In generalized linear models: <span class="math inline">\(f(\mu_i) = \beta_0 + \beta_1x_{1,i} ...\)</span> (which means, a function of the expected value of y)</p></li>
</ul>
</section>
<section id="the-deterministic-component-is-linear" class="slide level2">
<h2>The deterministic component is linear</h2>
<p>Which is a good thing! Each linear (not polynomial… let’s forget about that for a little while) has two components!</p>
<ul>
<li class="fragment"><p>A slope</p></li>
<li class="fragment"><p>An intercept</p></li>
</ul>
</section>
<section id="the-deterministic-component-is-linear-1" class="slide level2">
<h2>The deterministic component is linear</h2>
<p>Which is a good thing! Each linear (not polynomial… let’s forget about that for a little while) has two components!</p>
<div>
<ul>
<li><p>A slope</p></li>
<li><p>An intercept</p></li>
</ul>
</div>
<p><span class="math display">\[
y = mx + b
\]</span></p>
</section>
<section id="the-deterministic-component-is-linear-2" class="slide level2">
<h2>The deterministic component is linear</h2>
<p>Which is a good thing! Each linear (not polynomial… let’s forget about that for a little while) has two components!</p>
<div>
<ul>
<li><p>A slope</p></li>
<li><p>An intercept</p></li>
</ul>
</div>
<p><span class="math display">\[
y = mx + b = b + mx
\]</span></p>
<p>is not any different than:</p>
<p><span class="math display">\[
\begin{align}
\mu_i &amp; = \beta_0 + \beta_1x_{1,i} \\
y_i &amp; ~ N(mean = \mu_i, var=\sigma^2)
\end{align}
\]</span></p>
</section>
<section id="lets-remember-what-a-slope-and-an-intercept-is" class="slide level2">
<h2>Let’s remember what a slope and an intercept is</h2>

<img data-src="pres-glm2_files/figure-revealjs/unnamed-chunk-2-1.png" width="960" class="r-stretch"></section>
<section id="lets-remember-what-a-slope-and-an-intercept-is-1" class="slide level2">
<h2>Let’s remember what a slope and an intercept is</h2>

<img data-src="pres-glm2_files/figure-revealjs/unnamed-chunk-3-1.png" width="960" class="r-stretch"></section>
<section id="lets-remember-what-a-slope-and-an-intercept-is-2" class="slide level2">
<h2>Let’s remember what a slope and an intercept is</h2>

<img data-src="pres-glm2_files/figure-revealjs/unnamed-chunk-4-1.png" width="960" class="r-stretch"></section>
<section id="lets-remember-what-a-slope-and-an-intercept-is-3" class="slide level2">
<h2>Let’s remember what a slope and an intercept is</h2>

<img data-src="pres-glm2_files/figure-revealjs/unnamed-chunk-5-1.png" width="960" class="r-stretch"><ul>
<li class="fragment"><p>Slope: For very change in x of 1, y changes 1.5. Intercept: 2</p></li>
<li class="fragment"><p>So, if x = 5, then y = 2 + 1.5(5) = 9.5</p></li>
</ul>
</section>
<section id="so-what-about-linear-models" class="slide level2">
<h2>So, what about linear models?</h2>
<p>Each line in a linear model simply has: 1 slope and 1 intercept.</p>

<img data-src="pres-glm2_files/figure-revealjs/unnamed-chunk-6-1.png" width="960" class="r-stretch"></section>
<section id="so-what-about-linear-models-1" class="slide level2">
<h2>So, what about linear models?</h2>
<p>What is the slope? what is the intercept?</p>

<img data-src="pres-glm2_files/figure-revealjs/unnamed-chunk-7-1.png" width="960" class="r-stretch"></section>
<section id="so-what-about-linear-models-2" class="slide level2">
<h2>So, what about linear models?</h2>
<p><span class="math display">\[
\begin{split}
y_i &amp; \sim \beta_0 + \beta_1x_i + \epsilon_i \\
\text{where } \epsilon &amp; \sim normal(0,\sigma)
\end{split}
\]</span> Or, in this specific case:</p>
<p><span class="math display">\[
Reproductive \ effort_i \sim \beta_0 + \beta_1Food \ availability_i + \epsilon_i \\
\]</span></p>
</section>
<section id="so-what-about-linear-models-3" class="slide level2">
<h2>So, what about linear models?</h2>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = ReproductiveEffort ~ Foodavailability, data = foodav)

Residuals:
     Min       1Q   Median       3Q      Max 
-0.37653 -0.25549 -0.04903  0.23662  0.45750 

Coefficients:
                 Estimate Std. Error t value Pr(&gt;|t|)    
(Intercept)       0.89490    0.07262   12.32   &lt;2e-16 ***
Foodavailability  1.19387    0.01590   75.08   &lt;2e-16 ***
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 0.2652 on 61 degrees of freedom
Multiple R-squared:  0.9893,    Adjusted R-squared:  0.9891 
F-statistic:  5636 on 1 and 61 DF,  p-value: &lt; 2.2e-16</code></pre>
</div>
</div>
<p>Intercept: 0.895</p>
<p>Slope: 1.194</p>
<p><span class="math display">\[
\begin{split}
y_i &amp; \sim \beta_0 + \beta_1x_i + \epsilon_i \\
\text{where } \epsilon &amp; \sim normal(0,\sigma)
\end{split}
\]</span></p>
</section>
<section id="results" class="slide level2">
<h2>Results</h2>
<table class="caption-top">
<thead>
<tr class="header">
<th>Coefficient1</th>
<th>Estimate</th>
<th>Col3</th>
<th>Col4</th>
<th>Col5</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Intercept <span class="math inline">\(\beta_0\)</span></td>
<td>0.895</td>
<td></td>
<td></td>
<td></td>
</tr>
<tr class="even">
<td>Slope <span class="math inline">\(\beta_1\)</span></td>
<td>1.194</td>
<td></td>
<td></td>
<td></td>
</tr>
</tbody>
</table>
<p><span class="math display">\[
\begin{split}
y_i &amp; \sim \beta_0 + \beta_1x_i + \epsilon_i \\
\text{where } \epsilon &amp; \sim normal(0,\sigma)
\end{split}
\]</span></p>
</section>
<section id="results-1" class="slide level2">
<h2>Results</h2>
<table class="caption-top">
<colgroup>
<col style="width: 30%">
<col style="width: 14%">
<col style="width: 17%">
<col style="width: 23%">
<col style="width: 14%">
</colgroup>
<thead>
<tr class="header">
<th>Coefficient1</th>
<th>Estimate</th>
<th>Std. Error</th>
<th>t-value (test)</th>
<th>Col5</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Intercept <span class="math inline">\(\beta_0\)</span></td>
<td>0.895</td>
<td>0.072</td>
<td>12.32</td>
<td>&lt;0.0001</td>
</tr>
<tr class="even">
<td>Slope <span class="math inline">\(\beta_1\)</span></td>
<td>1.194</td>
<td>0.0159</td>
<td>75.08</td>
<td>&lt;0.0001</td>
</tr>
</tbody>
</table>
<p><span class="math display">\[ \begin{split} y_i &amp; \sim \beta_0 + \beta_1x_i + \epsilon_i \\ \text{where } \epsilon &amp; \sim normal(0,\sigma) \end{split} \]</span></p>
<p>Test:</p>
<p>Ho: Coefficient == 0</p>
<p>Ha Coefficient != 0</p>
</section>
<section id="how-about-this-one" class="slide level2">
<h2>How about this one:</h2>

<img data-src="pres-glm2_files/figure-revealjs/unnamed-chunk-9-1.png" width="960" class="r-stretch"></section>
<section id="how-about-this-one-1" class="slide level2">
<h2>How about this one:</h2>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = FC ~ IC + Dose, data = drugz)

Residuals:
    Min      1Q  Median      3Q     Max 
-2.2610 -0.6360  0.0000  0.6514  2.2876 

Coefficients:
            Estimate Std. Error t value Pr(&gt;|t|)    
(Intercept)  0.51804    0.38892   1.332   0.1849    
IC           0.93384    0.05647  16.537   &lt;2e-16 ***
Dosedose1   -0.44007    0.20011  -2.199   0.0294 *  
Dosedose2   -2.09915    0.20162 -10.412   &lt;2e-16 ***
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 0.9893 on 146 degrees of freedom
Multiple R-squared:  0.7636,    Adjusted R-squared:  0.7588 
F-statistic: 157.2 on 3 and 146 DF,  p-value: &lt; 2.2e-16</code></pre>
</div>
</div>
<ul>
<li class="fragment">Additive model means only one slope is estimated!</li>
</ul>
</section>
<section id="back-to-the-plot" class="slide level2">
<h2>Back to the plot</h2>

<img data-src="pres-glm2_files/figure-revealjs/unnamed-chunk-11-1.png" width="960" class="r-stretch"><ul>
<li class="fragment"><p>Parallel lines</p></li>
<li class="fragment"><p>1 slope, 3 intercepts</p></li>
<li class="fragment"><p>Each line: <span class="math inline">\(y = mx + b\)</span></p></li>
</ul>
</section>
<section id="finding-values" class="slide level2">
<h2>Finding values</h2>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = FC ~ IC + Dose, data = drugz)

Residuals:
    Min      1Q  Median      3Q     Max 
-2.2610 -0.6360  0.0000  0.6514  2.2876 

Coefficients:
            Estimate Std. Error t value Pr(&gt;|t|)    
(Intercept)  0.51804    0.38892   1.332   0.1849    
IC           0.93384    0.05647  16.537   &lt;2e-16 ***
Dosedose1   -0.44007    0.20011  -2.199   0.0294 *  
Dosedose2   -2.09915    0.20162 -10.412   &lt;2e-16 ***
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 0.9893 on 146 degrees of freedom
Multiple R-squared:  0.7636,    Adjusted R-squared:  0.7588 
F-statistic: 157.2 on 3 and 146 DF,  p-value: &lt; 2.2e-16</code></pre>
</div>
</div>
<p><span class="math display">\[
\begin{align}
\beta_0 &amp; = 0.51 \ \text{intercept for control} \\
\beta_1 &amp; = 0.93 \ \text{slope} \\
\beta_2 &amp; = -0.44 \ \text{Difference in intercept between control and dose 1} \\
\beta_2 &amp; = -2.099 \ \text{Difference in intercept between control and dose 2} \\
\end{align}
\]</span></p>
<p><span class="math display">\[
y_i \sim \beta_0 + \beta_1x_{1,i}  + \beta_2x_{2,i} +  \beta_3x_{3,i} + \epsilon_i \\
\]</span></p>
<table class="caption-top">
<thead>
<tr class="header">
<th>Site</th>
<th>Value of <span class="math inline">\(x_2\)</span></th>
<th>Value of <span class="math inline">\(x_3\)</span></th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Control</td>
<td>0</td>
<td>0</td>
</tr>
<tr class="even">
<td>Dose 1</td>
<td>1</td>
<td>0</td>
</tr>
<tr class="odd">
<td>Dose 2</td>
<td>0</td>
<td>1</td>
</tr>
</tbody>
</table>
</section>
<section id="finding-values-1" class="slide level2">
<h2>Finding values</h2>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = FC ~ IC + Dose, data = drugz)

Residuals:
    Min      1Q  Median      3Q     Max 
-2.2610 -0.6360  0.0000  0.6514  2.2876 

Coefficients:
            Estimate Std. Error t value Pr(&gt;|t|)    
(Intercept)  0.51804    0.38892   1.332   0.1849    
IC           0.93384    0.05647  16.537   &lt;2e-16 ***
Dosedose1   -0.44007    0.20011  -2.199   0.0294 *  
Dosedose2   -2.09915    0.20162 -10.412   &lt;2e-16 ***
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 0.9893 on 146 degrees of freedom
Multiple R-squared:  0.7636,    Adjusted R-squared:  0.7588 
F-statistic: 157.2 on 3 and 146 DF,  p-value: &lt; 2.2e-16</code></pre>
</div>
</div>
<table class="caption-top">
<thead>
<tr class="header">
<th>Measurement</th>
<th>Intercept</th>
<th>Slope</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Control</td>
<td>0.51</td>
<td>0.93</td>
</tr>
<tr class="even">
<td>Dose 1</td>
<td>0.51 - 0.44</td>
<td>0.93</td>
</tr>
<tr class="odd">
<td>Dose 2</td>
<td>0.51 -2.099</td>
<td>0.93</td>
</tr>
</tbody>
</table>
</section>
<section id="statistical-inference" class="slide level2">
<h2>Statistical inference</h2>
<p><code>anova</code></p>
<p><code>emmeans</code></p>
<p><code>contrast</code></p>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code>Analysis of Variance Table

Response: FC
           Df Sum Sq Mean Sq F value    Pr(&gt;F)    
IC          1 342.36  342.36 349.825 &lt; 2.2e-16 ***
Dose        2 119.30   59.65  60.949 &lt; 2.2e-16 ***
Residuals 146 142.89    0.98                      
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1</code></pre>
</div>
<div class="cell-output cell-output-stdout">
<pre><code> contrast        estimate    SE  df t.ratio p.value
 control - dose1     0.44 0.200 146   2.199  0.0747
 control - dose2     2.10 0.202 146  10.412  &lt;.0001
 dose1 - dose2       1.66 0.198 146   8.377  &lt;.0001

P value adjustment: tukey method for comparing a family of 3 estimates </code></pre>
</div>
</div>
</section>
<section id="statistical-inference-1" class="slide level2">
<h2>statistical inference</h2>
<p><code>anova</code> compares variance. Is the variance between groups higher than within groups?</p>

<img data-src="images/clipboard-4150061290.png" class="r-stretch"></section>
<section id="interactive" class="slide level2">
<h2>Interactive</h2>

<img data-src="pres-glm2_files/figure-revealjs/unnamed-chunk-15-1.png" width="960" class="r-stretch"><ul>
<li class="fragment">Each line has its own slope and its own intercept</li>
</ul>
</section>
<section id="interactive-1" class="slide level2">
<h2>Interactive</h2>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = FC ~ IC * Dose, data = drugz)

Residuals:
    Min      1Q  Median      3Q     Max 
-2.3167 -0.6262 -0.0031  0.6443  2.1836 

Coefficients:
             Estimate Std. Error t value Pr(&gt;|t|)    
(Intercept)   0.38733    0.59401   0.652   0.5154    
IC            0.95418    0.08981  10.624   &lt;2e-16 ***
Dosedose1     0.07353    0.85237   0.086   0.9314    
Dosedose2    -2.21858    0.86308  -2.571   0.0112 *  
IC:Dosedose1 -0.08529    0.13509  -0.631   0.5288    
IC:Dosedose2  0.02324    0.13917   0.167   0.8676    
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 0.9939 on 144 degrees of freedom
Multiple R-squared:  0.7647,    Adjusted R-squared:  0.7565 
F-statistic: 93.59 on 5 and 144 DF,  p-value: &lt; 2.2e-16</code></pre>
</div>
</div>
<p><span class="math display">\[
\begin{align}
\beta_0 &amp; = 0.38 \ \text{intercept for control} \\
\beta_1 &amp; = 0.954 \ \text{slope for control} \\
\beta_2 &amp; = -0.073 \ \text{Difference in intercept between control and dose 1} \\
\beta_3 &amp; = -2.24 \ \text{Difference in intercept between control and dose 2} \\
\beta_4 &amp; = -0.085 \ \text{Difference in slope between control and dose 1} \\
\beta_5 &amp; = 0.023 \ \text{Difference in slope between control and dose 2} \\
\end{align}
\]</span></p>
<table class="caption-top">
<colgroup>
<col style="width: 12%">
<col style="width: 21%">
<col style="width: 21%">
<col style="width: 21%">
<col style="width: 21%">
</colgroup>
<thead>
<tr class="header">
<th>Site</th>
<th>Value of <span class="math inline">\(x_2\)</span></th>
<th>Value of <span class="math inline">\(x_3\)</span></th>
<th>Value of <span class="math inline">\(x_4\)</span></th>
<th>Value of <span class="math inline">\(x_5\)</span></th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Control</td>
<td>0</td>
<td>0</td>
<td>0</td>
<td>0</td>
</tr>
<tr class="even">
<td>Dose 1</td>
<td>1</td>
<td>0</td>
<td>1</td>
<td>0</td>
</tr>
<tr class="odd">
<td>Dose 2</td>
<td>0</td>
<td>1</td>
<td>0</td>
<td>1</td>
</tr>
</tbody>
</table>
</section>
<section id="doing-inference-of-interactions" class="slide level2">
<h2>Doing inference of interactions</h2>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code>Analysis of Variance Table

Response: FC
           Df Sum Sq Mean Sq  F value Pr(&gt;F)    
IC          1 342.36  342.36 346.5514 &lt;2e-16 ***
Dose        2 119.30   59.65  60.3790 &lt;2e-16 ***
IC:Dose     2   0.63    0.31   0.3168  0.729    
Residuals 144 142.26    0.99                    
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1</code></pre>
</div>
<div class="cell-output cell-output-stdout">
<pre><code> contrast        estimate    SE  df t.ratio p.value
 control - dose1     0.44 0.202 144   2.173  0.0794
 control - dose2     2.08 0.204 144  10.175  &lt;.0001
 dose1 - dose2       1.64 0.201 144   8.136  &lt;.0001

P value adjustment: tukey method for comparing a family of 3 estimates </code></pre>
</div>
</div>
</section>
<section id="interactions" class="slide level2">
<h2>Interactions</h2>

<img data-src="pres-glm2_files/figure-revealjs/unnamed-chunk-18-1.png" width="960" class="r-stretch"></section>
<section id="finding-values-predictions" class="slide level2 scrollable">
<h2>Finding values (predictions)</h2>
<div class="callout callout-important callout-titled callout-style-default">
<div class="callout-body">
<div class="callout-title">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<p><strong>Assignment question 1 📝</strong></p>
</div>
<div class="callout-content">
<p>Look at the summary. And before continuing make sure you understand it. If you don’t, now is the time to raise your hand.</p>
<p>You need to calculate the expected probability (we’ll call this <span class="math inline">\(\pi\)</span>) of an individual being infected for each of the following two cases:</p>
<ol type="1">
<li class="fragment">An individual of length 50 from Area 1, in 1999</li>
<li class="fragment">An individual of length 50 from Area 3, in 2001</li>
</ol>
</div>
</div>
</div>
</section>
<section id="glm" class="slide level2">
<h2>GLM</h2>

<img data-src="pres-glm2_files/figure-revealjs/unnamed-chunk-19-1.png" width="960" class="r-stretch"></section>
<section id="model" class="slide level2">
<h2>Model</h2>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code>'data.frame':   1254 obs. of  12 variables:
 $ Sample    : int  1 2 3 4 5 6 7 8 9 10 ...
 $ Intensity : int  0 0 0 0 0 0 0 0 0 0 ...
 $ Prevalence: int  0 0 0 0 0 0 0 0 0 0 ...
 $ Year      : Factor w/ 3 levels "1999","2000",..: 1 1 1 1 1 1 1 1 1 1 ...
 $ Depth     : int  220 220 220 220 220 220 220 194 194 194 ...
 $ Weight    : int  148 144 146 138 40 68 52 3848 2576 1972 ...
 $ Length    : int  26 26 27 26 17 20 19 77 67 60 ...
 $ Sex       : Factor w/ 3 levels "0","1","2": 1 1 1 1 1 1 1 1 1 1 ...
 $ Stage     : Factor w/ 5 levels "0","1","2","3",..: 1 1 1 1 1 1 1 1 1 1 ...
 $ Age       : int  0 0 0 0 0 0 0 0 0 0 ...
 $ Area      : Factor w/ 4 levels "1","2","3","4": 2 2 2 2 2 2 2 3 3 3 ...
 $ WL2       : num  19.2 18.7 19.7 17.9 3.4 ...</code></pre>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>     Sample Intensity Prevalence Year Depth Weight Length Sex Stage Age Area
1         1         0          0 1999   220    148     26   0     0   0    2
2         2         0          0 1999   220    144     26   0     0   0    2
3         3         0          0 1999   220    146     27   0     0   0    2
4         4         0          0 1999   220    138     26   0     0   0    2
5         5         0          0 1999   220     40     17   0     0   0    2
6         6         0          0 1999   220     68     20   0     0   0    2
7         7         0          0 1999   220     52     19   0     0   0    2
8         8         0          0 1999   194   3848     77   0     0   0    3
9         9         0          0 1999   194   2576     67   0     0   0    3
10       10         0          0 1999   194   1972     60   0     0   0    3
11       11         0          0 1999   194   2272     62   0     0   0    3
12       12         0          0 1999   194   1046     49   0     0   0    3
13       13         0          0 1999   194   1186     52   0     0   0    3
14       14         0          0 1999   194    776     45   0     0   0    3
15       15         0          0 1999   194   2372     61   0     0   0    3
16       16         0          0 1999   194   1194     54   0     0   0    3
17       17         0          0 1999   194   3574     71   0     0   0    3
18       18         0          0 1999   194   2138     65   0     0   0    3
19       19         0          0 1999   194   2222     59   0     0   0    3
20       20         0          0 1999   194   2482     62   0     0   0    3
21       21         0          0 1999   194   2164     61   0     0   0    3
22       22         0          0 1999   194   1772     57   0     0   0    3
23       23         0          0 1999   194    494     39   0     0   0    3
24       24         0          0 1999   194   3130     67   0     0   0    3
25       25         0          0 1999   194   2708     65   0     0   0    3
26       26         0          0 1999   194   2394     66   0     0   0    3
27       27         0          0 1999   194   2212     64   0     0   0    3
28       28         0          0 1999   194   3110     65   0     0   0    3
29       29         0          0 1999   194   2218     62   0     0   0    3
30       30         0          0 1999   194   2222     60   0     0   0    3
31       31         0          0 1999   194   2398     62   0     0   0    3
32       32         0          0 1999   235    368     35   0     0   0    4
33       33         0          0 1999   235    306     34   0     0   0    4
34       34         0          0 1999   235    318     35   0     0   0    4
35       35         0          0 1999   235    276     32   0     0   0    4
36       36         0          0 1999   278     84     22   0     0   0    4
37       37         0          0 1999    51   1016     47   2     1   3    1
38       38         0          0 1999    51   1584     53   1     1   5    1
39       39         0          0 1999    51   1354     55   1     1   4    1
40       40         0          0 1999    51   1518     52   1     1   4    1
41       41         0          0 1999    51   1382     51   2     1   4    1
42       42         0          0 1999    51   1648     55   1     1   4    1
43       43         0          0 1999    51   1354     51   2     1   5    1
44       44         0          0 1999    51   1870     54   2     1   5    1
45       45         0          0 1999    51   1272     53   2     1   5    1
46       46         0          0 1999    51   1360     50   1     1   4    1
47       47         0          0 1999    51    936     45   2     1   3    1
48       48         0          0 1999    51   1650     55   2     1   5    1
49       49         0          0 1999    51   1504     53   1     1   5    1
50       50         0          0 1999    51   1008     48   2     1   3    1
51       51         0          0 1999    51    896     46   2     1   3    1
52       52         0          0 1999    51   3016     68   1     1   5    1
53       53         0          0 1999    85    470     37   1     1   2    1
54       54         0          0 1999    85    520     38   1     1   2    1
55       55         0          0 1999    85    470     38   1     1   2    1
56       56         0          0 1999    85    558     39   2     1   3    1
57       57         0          0 1999    85   3076     68   2     1   5    1
58       58         0          0 1999    85   1536     57   2     1   4    1
59       59         0          0 1999    85   1916     60   2     1   4    1
60       60         0          0 1999    85    320     32   1     1   2    1
61       61         0          0 1999    85   1152     49   1     1   4    1
62       62         0          0 1999    85   1284     54   1     1   5    1
63       63         0          0 1999    85   4712     80   1     1   7    1
64       64         0          0 1999    85   2182     60   2     1   4    1
65       65         0          0 1999    85    976     49   1     1   3    1
66       66         0          0 1999    85    408     36   1     1   2    1
67       67         0          0 1999    85    242     30   2     1   2    1
68       68         0          0 1999    85    644     41   2     1   3    1
69       69         0          0 1999    85    540     39   2     1   2    1
70       70         0          0 1999    85    326     33   1     1   2    1
71       71         0          0 1999    85    300     33   1     1   2    1
72       72         0          0 1999    85    232     29   2     1   2    1
73       73         0          0 1999    85    822     45   1     1   3    1
74       74         0          0 1999    85    692     43   1     1   3    1
75       75         0          0 1999    85    438     36   2     1   2    1
76       76         0          0 1999    85    406     35   2     1   2    1
77       77         0          0 1999    85    240     30   2     1   2    1
78       78         0          0 1999    85    358     34   1     1   2    1
79       79         0          0 1999   137    476     38   2     1   3    1
80       80         0          0 1999   137   1478     55   1     1   4    1
81       81         0          0 1999   137   1672     57   1     1   5    1
82       82         0          0 1999   137   1582     56   2     1   3    1
83       83         0          0 1999   137    390     35   2     1   2    1
84       84         0          0 1999   150   1816     59   1     1   5    2
85       85         0          0 1999   150   3888     71   1     1   5    2
86       86         0          0 1999   150   1986     58   1     1   4    2
87       87         0          0 1999   150   2524     66   1     1   5    2
88       88         0          0 1999   150   1712     59   2     1   4    2
89       89         0          0 1999   150   1968     58   2     1   4    2
90       90         0          0 1999   150   2764     64   1     1   5    2
91       91         0          0 1999   150   3412     69   1     1   5    2
92       92         0          0 1999   150   2294     63   1     1   5    2
93       93         0          0 1999   150    552     38   1     1   2    2
94       94         0          0 1999   150   1422     54   2     1   4    2
95       95         0          0 1999   150   1028     47   2     1   3    2
96       96         0          0 1999   150    466     38   2     1   2    2
97       97         0          0 1999   150    432     35   1     1   2    2
98       98         0          0 1999   150    300     31   2     1   2    2
99       99         0          0 1999   150   2706     67   1     1   5    2
100     100         0          0 1999   150   1154     52   1     1   3    2
101     101         0          0 1999   150   1146     52   1     1   4    2
102     102         0          0 1999   100   2352     64   1     1   6    2
103     103         0          0 1999   100   2084     60   2     1   4    2
104     104         0          0 1999   100   1008     48   2     1   3    2
105     105         0          0 1999   100   3970     73   2     1   5    2
106     106         0          0 1999   100   1738     55   2     1   5    2
107     107         0          0 1999   100    844     45   2     1   3    2
108     108         0          0 1999   100   3688     74   1     1   6    2
109     109         0          0 1999   100   2848     67   1     1   5    2
110     110         0          0 1999   100   1090     47   2     1   3    2
111     111         0          0 1999   292    826     49   2     1   3    2
112     112         0          0 1999   220   2086     61   1     1   5    2
113     113         0          0 1999   220   1744     58   2     1   5    2
114     114         0          0 1999   220   2118     60   1     1   5    2
115     115         0          0 1999   220    750     45   2     1   3    2
116     116         0          0 1999   220   1570     58   2     1   5    2
117     117         0          0 1999   220    326     33   2     1   2    2
118     118         0          0 1999   220   4292     77   1     1   6    2
119     119         0          0 1999   220    220     30   1     1   2    2
120     120         0          0 1999   220    262     32   2     1   2    2
121     121         0          0 1999   220    184     28   1     1   2    2
122     122         0          0 1999   220    180     28   1     1   2    2
123     123         0          0 1999   220    976     48   1     1   3    2
124     124         0          0 1999   220   1344     52   2     1   4    2
125     125         0          0 1999   220   2926     67   1     1   5    2
126     126         0          0 1999   220    544     41   1     1   3    2
127     127         0          0 1999   220    774     44   2     1   3    2
128     128         0          0 1999   220    452     37   2     1   2    2
129     129         0          0 1999   220    258     32   1     1   2    2
130     130         0          0 1999   220    190     29   2     1   2    2
131     131         0          0 1999   220    266     32   1     1   2    2
132     132         0          0 1999   220    196     29   1     1   0    2
133     133         0          0 1999    99   1846     59   1     1   4    3
134     134         0          0 1999    99   1312     53   2     1   4    3
135     135         0          0 1999    99   3302     73   2     1   5    3
136     136         0          0 1999    99   1258     50   2     1   4    3
137     137         0          0 1999    99   1848     57   1     1   6    3
138     138         0          0 1999    99   1246     51   2     1   4    3
139     139         0          0 1999    99   2038     59   2     1   4    3
140     140         0          0 1999    99   4738     77   1     1   6    3
141     141         0          0 1999    99   1248     51   2     1   4    3
142     142         0          0 1999    99   1072     48   1     1   3    3
143     143         0          0 1999    99    854     46   2     1   3    3
144     144         0          0 1999    99   2168     62   2     1   4    3
145     145         0          0 1999    99   1108     50   2     1   4    3
146     146         0          0 1999    99   1122     50   1     1   4    3
147     147         0          0 1999    99   2050     61   1     1   4    3
148     148         0          0 1999    99   1168     51   2     1   4    3
149     149         0          0 1999    99   1334     53   2     1   4    3
150     150         0          0 1999    99    964     47   2     1   3    3
151     151         0          0 1999    99    678     41   2     1   2    3
152     152         0          0 1999    99   1076     49   2     1   4    3
153     153         0          0 1999    99   1238     52   1     1   4    3
154     154         0          0 1999    99   1824     58   1     1   4    3
155     155         0          0 1999    99    860     44   1     1   3    3
156     156         0          0 1999    99   1260     50   2     1   4    3
157     157         0          0 1999    99   1154     52   1     1   4    3
158     158         0          0 1999    99    936     43   1     1   3    3
159     159         0          0 1999    99   1598     55   2     1   4    3
160     160         0          0 1999    99   2500     65   2     1   5    3
161     161         0          0 1999    99   1942     59   1     1   4    3
162     162         0          0 1999   270    770     47   2     1   4    3
163     163         0          0 1999   270    538     40   2     1   3    3
164     164         0          0 1999   270   3862     78   1     1   6    3
165     165         0          0 1999   270    878     48   2     1   4    3
166     166         0          0 1999   270   1438     55   1     1   4    3
167     167         0          0 1999   270   1592     59   2     1   5    3
168     168         0          0 1999   270   1250     53   2     1   4    3
169     169         0          0 1999   270   1226     51   1     1   4    3
170     170         0          0 1999   270   1326     53   1     1   4    3
171     171         0          0 1999   270   1104     49   2     1   4    3
172     172         0          0 1999   270   1982     63   2     1   5    3
173     173         0          0 1999   270   2480     64   1     1   5    3
174     174         0          0 1999   270   1142     51   2     1   4    3
175     175         0          0 1999   270    488     39   1     1   4    3
176     176         0          0 1999   270   1382     55   1     1   4    3
177     177         0          0 1999   256   1714     59   2     1   4    3
178     178         0          0 1999   256    754     45   1     1   4    3
179     179         0          0 1999   256   1618     61   1     1   5    3
180     180         0          0 1999   256   2122     64   2     1   5    3
181     181         0          0 1999   256    604     38   1     1   3    3
182     182         0          0 1999   256   2780     65   1     1   6    3
183     183         0          0 1999   256   2318     64   1     1   4    3
184     184         0          0 1999   256   1344     53   1     1   4    3
185     185         0          0 1999   256   1674     60   2     1   8    3
186     186         0          0 1999   256   1144     53   1     1   7    3
187     187         0          0 1999   256   1052     51   2     1   3    3
188     188         0          0 1999   172   2034     57   2     1   5    3
189     189         0          0 1999   172    674     42   2     1   3    3
190     190         0          0 1999   172    862     47   1     1   3    3
191     191         0          0 1999   172    612     40   1     1   3    3
192     192         0          0 1999   172   2528     64   2     1   4    3
193     193         0          0 1999   172   1516     55   1     1   4    3
194     194         0          0 1999   172    906     47   1     1   4    3
195     195         0          0 1999   172    434     38   2     1   3    3
196     196         0          0 1999   172    182     29   1     1   2    3
197     197         0          0 1999   172    230     31   1     1   2    3
198     198         0          0 1999   172    200     29   1     1   2    3
199     199         0          0 1999   172    222     29   1     1   2    3
200     200         0          0 1999   172    238     30   2     1   2    3
201     201         0          0 1999   172    176     28   2     1   2    3
202     202         0          0 1999   172    198     30   1     1   2    3
203     203         0          0 1999   172    168     29   1     1   2    3
204     204         0          0 1999   172    170     28   1     1   2    3
205     205         0          0 1999   172    204     30   2     1   2    3
206     206         0          0 1999   235   2496     68   1     1   6    4
207     207         0          0 1999   235   1198     50   2     1   3    4
208     208         0          0 1999   235   3678     75   1     1   5    4
209     209         0          0 1999   235   1036     50   1     1   4    4
210     210         0          0 1999   235   2898     73   1     1   5    4
211     211         0          0 1999   278    582     40   1     1   3    4
212     212         0          0 1999   278    986     48   2     1   4    4
213     213         0          0 1999   278    662     44   2     1   3    4
214     214         0          0 1999   278    270     33   1     1   2    4
215     215         0          0 1999   278    980     49   2     1   3    4
216     216         0          0 1999   278   1330     52   1     1   4    4
217     217         0          0 1999   278    364     36   2     1   2    4
218     218         0          0 1999   110   3190     68   2     1   6    4
219     219         0          0 1999   110    626     42   1     1   3    4
220     220         0          0 1999   110    788     46   1     1   3    4
221     221         0          0 1999   110    968     51   2     1   5    4
222     222         0          0 1999   110   1322     54   1     1   4    4
223     223         0          0 1999   110   1400     54   2     1   4    4
224     224         0          0 1999   110    942     48   2     1   4    4
225     225         0          0 1999   110   1104     53   2     1   4    4
226     226         0          0 1999   110    500     40   1     1   3    4
227     227         0          0 1999   110    296     33   2     1   2    4
228     228         0          0 1999   110    168     29   1     1   2    4
229     229         0          0 1999   110    370     36   1     1   3    4
230     230         0          0 1999    51   1544     53   2     2   4    1
231     231         0          0 1999    51   1520     53   2     2   4    1
232     232         0          0 1999    51   1912     58   1     2   6    1
233     233         0          0 1999    51   1144     49   2     2   4    1
234     234         0          0 1999    51   1472     51   2     2   4    1
235     235         0          0 1999    51   1418     51   2     2   5    1
236     236         0          0 1999    51   1330     49   2     2   3    1
237     237         0          0 1999    85    948     47   2     2   3    1
238     238         0          0 1999   200   2292     65   1     2   6    1
239     239         0          0 1999   200   2562     63   1     2   6    1
240     240         0          0 1999   100   1708     55   2     2   5    2
241     241         0          0 1999   100   1670     55   2     2   5    2
242     242         0          0 1999   100   1740     57   2     2   5    2
243     243         0          0 1999   100   2396     62   2     2   5    2
244     244         0          0 1999   220   3484     68   2     2   6    2
245     245         0          0 1999    99   2896     64   2     2   7    3
246     246         0          0 1999    99   1712     55   2     2   4    3
247     247         0          0 1999    99   1778     57   1     2   5    3
248     248         0          0 1999    99   1800     55   2     2   4    3
249     249         0          0 1999    99   4086     77   1     2   9    3
250     250         0          0 1999    99   1772     57   2     2   5    3
251     251         0          0 1999    99   2140     62   1     2   5    3
252     252         0          0 1999    99   1116     49   2     2   4    3
253     253         0          0 1999    99   1844     56   2     2   7    3
254     254         0          0 1999    99   1344     51   2     2   5    3
255     255         0          0 1999   270   1110     54   1     2   5    3
256     256         0          0 1999   270   2228     63   2     2   6    3
257     257         0          0 1999   270   1864     58   2     2   5    3
258     258         0          0 1999   270   1266     51   2     2   4    3
259     259         0          0 1999   270   1082     49   2     2   4    3
260     260         0          0 1999   256   2958     63   2     2   5    3
261     261         0          0 1999   256   3198     66   1     2   5    3
262     262         0          0 1999   256   2490     61   2     2   5    3
263     263         0          0 1999   256   3618     70   2     2   5    3
264     264         0          0 1999   256   3034     68   2     2   4    3
265     265         0          0 1999   172   2244     62   2     2   7    3
266     266         0          0 1999   172   1754     55   1     2   5    3
267     267         0          0 1999   172    178     28   1     2   2    3
268     268         0          0 1999   235   1578     54   2     2   4    4
269     269         0          0 1999   278   2130     59   2     2   5    4
270     270         0          0 1999   110   1304     50   1     2   4    4
271     271         0          0 1999   110   4098     74   2     2   8    4
272     272         0          0 1999   110   6390     88   1     2   8    4
273     273         0          0 1999   150   7854     90   1     4   7    2
274     274         0          0 1999   150     NA     NA   1     4   8    2
275     275         0          0 1999   100   6916     86   1     4   9    2
276     276         0          0 1999   100   2980     65   1     4   7    2
277     277         0          0 1999   220   4018     72   1     4   6    2
278     278         0          0 1999   270   2552     63   1     4   5    3
279     279         0          0 2000    57   1474     51   1     1   6    1
280     280         0          0 2000    57   1608     57   2     1   6    1
281     281         0          0 2000    57    830     47   1     1   3    1
282     282         0          0 2000    50    992     48   2     1   3    1
283     283         0          0 2000   121    552     40   1     1   2    1
284     284         0          0 2000   121   1744     58   1     1   4    1
285     285         0          0 2000   121    668     42   1     1   2    1
286     286         0          0 2000   121    448     36   1     1   2    1
287     287         0          0 2000   121    410     36   1     1   2    1
288     288         0          0 2000   121   1222     51   1     1   3    1
289     289         0          0 2000   102   1538     54   1     1   4    2
290     290         0          0 2000   102   2820     62   1     1   6    2
291     291         0          0 2000   102   1116     49   2     1   3    2
292     292         0          0 2000   102   4058     75   2     1   6    2
293     293         0          0 2000   102    544     40   1     1   2    2
294     294         0          0 2000   102    398     35   2     1   2    2
295     295         0          0 2000   102    514     39   2     1   2    2
296     296         0          0 2000   102   1124     48   2     1   4    2
297     297         0          0 2000   102   1038     48   1     1   3    2
298     298         0          0 2000   102   1470     53   2     1   4    2
299     299         0          0 2000   102   4348     75   1     1   6    2
300     300         0          0 2000   102    440     36   2     1   2    2
301     301         0          0 2000   102   1984     59   2     1   6    2
302     302         0          0 2000   102   1966     61   1     1   4    2
303     303         0          0 2000   102   1094     49   2     1   4    2
304     304         0          0 2000   102    986     46   2     1   3    2
305     305         0          0 2000   293   3370     71   2     1   6    2
306     306         0          0 2000   293    920     46   2     1   3    2
307     307         0          0 2000   293   2394     66   2     1   7    2
308     308         0          0 2000   237    986     47   1     1   4    2
309     309         0          0 2000   237   1712     59   1     1   4    2
310     310         0          0 2000   237    506     39   2     1   3    2
311     311         0          0 2000   237    844     44   2     1   3    2
312     312         0          0 2000   237    292     31   1     1   2    2
313     313         0          0 2000   237   1364     52   2     1   4    2
314     314         0          0 2000   237   1056     50   1     1   3    2
315     315         0          0 2000   237   1746     56   2     1   5    2
316     316         0          0 2000   285   3618     77   2     1   5    3
317     317         0          0 2000   285   1546     55   1     1   4    3
318     318         0          0 2000   285   3388     70   2     1   5    3
319     319         0          0 2000   285   1328     55   2     1   5    3
320     320         0          0 2000   285    358     34   1     1   2    3
321     321         0          0 2000   285   1346     55   2     1   6    3
322     322         0          0 2000   285   4500     79   2     1   7    3
323     323         0          0 2000   285   1994     61   1     1   4    3
324     324         0          0 2000   285    930     47   2     1   4    3
325     325         0          0 2000   285    454     38   1     1   2    3
326     326         0          0 2000   285   1694     58   2     1   5    3
327     327         0          0 2000   285   1394     55   1     1   5    3
328     328         0          0 2000   285    922     49   1     1   4    3
329     329         0          0 2000   285   2196     62   1     1   5    3
330     330         0          0 2000   285   1734     59   2     1   5    3
331     331         0          0 2000   285    932     52   1     1   5    3
332     332         0          0 2000   285   3724     80   2     1   8    3
333     333         0          0 2000   285   1352     57   2     1   5    3
334     334         0          0 2000   285   2152     59   2     1   5    3
335     335         0          0 2000   285   1468     56   2     1   5    3
336     336         0          0 2000   285   2490     67   1     1   5    3
337     337         0          0 2000   285   1222     53   2     1   4    3
338     338         0          0 2000   285    208     30   1     1   2    3
339     339         0          0 2000   270   1404     55   1     1   4    4
340     340         0          0 2000   270   2366     59   2     1   5    4
341     341         0          0 2000   270    794     44   1     1   3    4
342     342         0          0 2000   260    314     33   1     1   2    4
343     343         0          0 2000   260    456     38   2     1   3    4
344     344         0          0 2000   260    508     41   2     1   2    4
345     345         0          0 2000   146   2858     67   2     1   6    3
346     346         0          0 2000   146    246     29   1     1   2    3
347     347         0          0 2000   146    276     32   2     1   2    3
348     348         0          0 2000    50   1370     51   2     2   5    1
349     349         0          0 2000   121   2882     67   1     2   6    1
350     350         0          0 2000   121   1950     60   2     2   6    1
351     351         0          0 2000   121   2428     63   2     2   5    1
352     352         0          0 2000   293   1622     54   2     2   5    2
353     353         0          0 2000   293   4672     81   1     2   6    2
354     354         0          0 2000   285   4228     76   2     2   6    3
355     355         0          0 2000   285   3174     73   2     2   7    3
356     356         0          0 2000   285   2262     64   2     2   5    3
357     357         0          0 2000   285   4498     79   2     2   6    3
358     358         0          0 2000   121   4434     77   1     4   6    1
359     359         0          0 2000   121   5476     78   1     4  10    1
360     360         0          0 2000   102     NA     NA   1     4   9    2
361     361         0          0 2000   102   2014     56   1     4   6    2
362     362         0          0 2000   102   4334     80   1     4   6    2
363     363         0          0 2000   146   1886     57   1     4   5    3
364     364         0          0 2000   146   6450     91   1     4   9    3
365     365         0          0 2001   193     34     17   0     0   1    3
366     366         0          0 2001    55    854     43   1     1   4    1
367     367         0          0 2001    55   1884     58   1     1   6    1
368     368         0          0 2001    55   1332     51   1     1   6    1
369     369         0          0 2001    55   1770     55   1     1   4    1
370     370         0          0 2001    55   1916     57   2     1   4    1
371     371         0          0 2001    55   1430     53   1     1   3    1
372     372         0          0 2001    55   1146     50   1     1   4    1
373     373         0          0 2001    55   1824     57   1     1   6    1
374     374         0          0 2001    55   1174     49   2     1   3    1
375     375         0          0 2001    55   1320     49   2     1   3    1
376     376         0          0 2001    55   1226     51   1     1   5    1
377     377         0          0 2001    90   1818     60   1     1   5    1
378     378         0          0 2001    90    956     47   1     1   4    1
379     379         0          0 2001    90    366     33   1     1   2    1
380     380         0          0 2001    90    278     30   1     1   2    1
381     381         0          0 2001    90    270     31   1     1   2    1
382     382         0          0 2001   112   1026     47   1     1   3    1
383     383         0          0 2001   112   1158     49   1     1   3    1
384     384         0          0 2001   112    354     35   1     1   2    1
385     385         0          0 2001   112    958     46   2     1   3    1
386     386         0          0 2001   112    268     31   1     1   2    1
387     387         0          0 2001   112    576     40   2     1   3    1
388     388         0          0 2001   112   2174     60   2     1   5    1
389     389         0          0 2001   112    500     36   1     1   2    1
390     390         0          0 2001   112    856     45   1     1   3    1
391     391         0          0 2001   112    640     40   1     1   2    1
392     392         0          0 2001   112    172     26   1     1   1    1
393     393         0          0 2001   112    392     35   1     1   2    1
394     394         0          0 2001   112    326     34   2     1   2    1
395     395         0          0 2001   112    188     28   1     1   1    1
396     396         0          0 2001   112    220     28   1     1   1    1
397     397         0          0 2001   112    170     26   2     1   1    1
398     398         0          0 2001   199   2788     72   1     1   6    2
399     399         0          0 2001   199   2178     63   1     1   5    2
400     400         0          0 2001   199    778     47   2     1   3    2
401     401         0          0 2001   199   1562     56   2     1   5    2
402     402         0          0 2001   199    764     43   1     1   3    2
403     403         0          0 2001   199   1458     55   2     1   4    2
404     404         0          0 2001   199   2092     63   1     1   6    2
405     405         0          0 2001   199    968     49   2     1   4    2
406     406         0          0 2001   199   1040     48   2     1   4    2
407     407         0          0 2001   199   3100     67   2     1   6    2
408     408         0          0 2001   199    346     37   1     1   2    2
409     409         0          0 2001   199    514     38   2     1   4    2
410     410         0          0 2001   199   3154     68   1     1   6    2
411     411         0          0 2001   199   1354     51   2     1   3    2
412     412         0          0 2001   199   3154     71   1     1   6    2
413     413         0          0 2001   199   1692     59   2     1   5    2
414     414         0          0 2001   199    886     46   1     1   3    2
415     415         0          0 2001   199    484     39   1     1   2    2
416     416         0          0 2001   199    242     32   1     1   2    2
417     417         0          0 2001    98   1316     54   2     1   4    3
418     418         0          0 2001    98   2464     63   1     1   4    3
419     419         0          0 2001    98   1770     57   1     1   3    3
420     420         0          0 2001    98    820     43   2     1   3    3
421     421         0          0 2001    98   1546     56   1     1   5    3
422     422         0          0 2001    98   1864     60   1     1   5    3
423     423         0          0 2001    98   2092     59   1     1   4    3
424     424         0          0 2001    98   2884     67   2     1   5    3
425     425         0          0 2001    98   1506     53   2     1   4    3
426     426         0          0 2001    98   1154     49   2     1   3    3
427     427         0          0 2001    98   1800     54   1     1   4    3
428     428         0          0 2001    98   1356     52   1     1   4    3
429     429         0          0 2001    98   1482     54   2     1   4    3
430     430         0          0 2001    98   1186     49   1     1   3    3
431     431         0          0 2001    98   1522     55   1     1   4    3
432     432         0          0 2001    98   1528     54   2     1   4    3
433     433         0          0 2001    98    610     40   1     1   3    3
434     434         0          0 2001    98   2038     62   1     1   4    3
435     435         0          0 2001    98    924     46   2     1   3    3
436     436         0          0 2001    98    404     36   2     1   2    3
437     437         0          0 2001    98   1026     49   1     1   3    3
438     438         0          0 2001    98   1108     51   1     1   3    3
439     439         0          0 2001    98   1462     53   1     1   3    3
440     440         0          0 2001    98   1466     54   2     1   4    3
441     441         0          0 2001    98   1496     56   1     1   4    3
442     442         0          0 2001   220   1566     56   2     1   4    4
443     443         0          0 2001   220   1678     60   1     1   4    4
444     444         0          0 2001   125   1742     62   2     1   5    4
445     445         0          0 2001   125   2362     65   2     1   4    4
446     446         0          0 2001   140   2088     63   1     1   3    4
447     447         0          0 2001   140   1108     49   2     1   3    4
448     448         0          0 2001   140   1040     49   2     1   4    4
449     449         0          0 2001   140    768     45   1     1   4    4
450     450         0          0 2001   140    832     46   2     1   3    4
451     451         0          0 2001   140   1388     55   2     1   4    4
452     452         0          0 2001   140   1028     48   1     1   4    4
453     453         0          0 2001   140    634     41   2     1   3    4
454     454         0          0 2001   140    508     38   2     1   3    4
455     455         0          0 2001   228   3096     71   1     1   6    4
456     456         0          0 2001   228   2476     66   1     1   5    4
457     457         0          0 2001   228    798     49   2     1   4    4
458     458         0          0 2001   228    648     43   2     1   3    4
459     459         0          0 2001   228    542     41   2     1   4    4
460     460         0          0 2001   228    452     39   2     1   3    4
461     461         0          0 2001   228    356     34   2     1   2    4
462     462         0          0 2001   228    202     29   2     1   1    4
463     463         0          0 2001   228    194     29   2     1   2    4
464     464         0          0 2001   228    110     24   2     1   2    4
465     465         0          0 2001   228     94     23   2     1   1    4
466     466         0          0 2001   228    130     26   2     1   1    4
467     467         0          0 2001   228     52     19   2     1   1    4
468     468         0          0 2001   228     40     17   2     1   1    4
469     469         0          0 2001   228     46     18   2     1   1    4
470     470         0          0 2001   180   1432     52   2     1   3    3
471     471         0          0 2001   180   2280     62   1     1   6    3
472     472         0          0 2001   180   1228     52   1     1   4    3
473     473         0          0 2001   180    544     38   1     1   3    3
474     474         0          0 2001   180    686     42   2     1   3    3
475     475         0          0 2001   180    506     36   1     1   2    3
476     476         0          0 2001   180    758     43   1     1   3    3
477     477         0          0 2001   180   1356     50   1     1   6    3
478     478         0          0 2001   180    994     47   1     1   4    3
479     479         0          0 2001   180   1608     54   2     1   4    3
480     480         0          0 2001   180   1014     47   1     1   3    3
481     481         0          0 2001   180    570     39   1     1   3    3
482     482         0          0 2001   180    710     44   1     1   3    3
483     483         0          0 2001   193   2834     71   2     1   5    3
484     484         0          0 2001   193   2018     62   2     1   4    3
485     485         0          0 2001   193   1746     57   1     1   4    3
486     486         0          0 2001   193   2552     66   1     1   5    3
487     487         0          0 2001   193    840     47   2     1   4    3
488     488         0          0 2001   193    240     31   2     1   2    3
489     489         0          0 2001   193    132     25   1     1   1    3
490     490         0          0 2001   193    212     29   2     1   2    3
491     491         0          0 2001   193    148     25   1     1   1    3
492     492         0          0 2001   193    152     27   2     1   2    3
493     493         0          0 2001   122   3372     72   1     1   6    3
494     494         0          0 2001   122   2314     68   2     1   5    3
495     495         0          0 2001   122   1680     61   2     1   5    3
496     496         0          0 2001   122   1272     54   2     1   4    3
497     497         0          0 2001   122    792     48   1     1   3    3
498     498         0          0 2001   122   2402     66   1     1   5    3
499     499         0          0 2001   122   1592     55   2     1   4    3
500     500         0          0 2001   122   1956     63   2     1   5    3
501     501         0          0 2001   122   1016     47   1     1   3    3
502     502         0          0 2001   122    208     29   1     1   2    3
503     503         0          0 2001   122    140     25   1     1   2    3
504     504         0          0 2001   122   1344     54   2     1   4    3
505     505         0          0 2001   122   1876     61   2     1   5    3
506     506         0          0 2001   122    694     43   1     1   3    3
507     507         0          0 2001   122    164     27   2     1   2    3
508     508         0          0 2001   122     46     18   2     1   1    3
509     509         0          0 2001   122     38     17   2     1   1    3
510     510         0          0 2001   256   2986     67   1     1   5    3
511     511         0          0 2001   256    900     48   2     1   3    3
512     512         0          0 2001   256   1240     52   1     1   3    3
513     513         0          0 2001   256    856     46   2     1   3    3
514     514         0          0 2001   256   1040     48   1     1   4    3
515     515         0          0 2001   256    482     38   2     1   3    3
516     516         0          0 2001   256   2624     69   1     1   6    3
517     517         0          0 2001   256    776     45   2     1   3    3
518     518         0          0 2001   256    816     44   1     1   3    3
519     519         0          0 2001   283   2450     65   2     1   6    2
520     520         0          0 2001   283   1534     55   2     1   4    2
521     521         0          0 2001   283   2342     62   1     1   5    2
522     522         0          0 2001   283   1608     54   1     1   6    2
523     523         0          0 2001   283   2608     59   1     1   7    2
524     524         0          0 2001   283    394     36   2     1   3    2
525     525         0          0 2001   283    502     38   1     1   3    2
526     526         0          0 2001   283   2692     63   1     1   8    2
527     527         0          0 2001   283   1384     49   1     1   5    2
528     528         0          0 2001   283   1292     53   1     1   3    2
529     529         0          0 2001   283    982     47   2     1   4    2
530     530         0          0 2001   260   3358     74   2     1   6    2
531     531         0          0 2001   260    360     35   2     1   2    2
532     532         0          0 2001   260    472     39   1     1   3    2
533     533         0          0 2001   276    154     26   1     1   1    2
534     534         0          0 2001   110   1376     52   1     1   4    2
535     535         0          0 2001   110   2548     62   1     1   5    2
536     536         0          0 2001   110   1614     54   1     1   4    2
537     537         0          0 2001   110   1374     51   1     1   4    2
538     538         0          0 2001   110   1516     54   1     1   3    2
539     539         0          0 2001   110    924     48   2     1   3    2
540     540         0          0 2001   110   2546     63   1     1   4    2
541     541         0          0 2001   110   1416     52   1     1   4    2
542     542         0          0 2001   110    420     35   2     1   2    2
543     543         0          0 2001   110    984     54   2     1   4    2
544     544         0          0 2001   110   1130     49   2     1   3    2
545     545         0          0 2001   110   3788     65   1     1   7    2
546     546         0          0 2001    55   2158     60   2     2   5    1
547     547         0          0 2001    55   1726     54   1     2   5    1
548     548         0          0 2001    55   1762     57   2     2   5    1
549     549         0          0 2001    55   1240     51   2     2   4    1
550     550         0          0 2001    55   1594     55   2     2   5    1
551     551         0          0 2001    55   1180     51   2     2   4    1
552     552         0          0 2001    55   1236     51   2     2   4    1
553     553         0          0 2001    55   1000     44   2     2   4    1
554     554         0          0 2001    55   2388     63   2     2   5    1
555     555         0          0 2001    55   1704     54   2     2   5    1
556     556         0          0 2001    55   1236     49   2     2   4    1
557     557         0          0 2001    55   1406     53   2     2   6    1
558     558         0          0 2001    55   1500     55   2     2   5    1
559     559         0          0 2001    55   1390     54   2     2   5    1
560     560         0          0 2001    55   1372     53   2     2   4    1
561     561         0          0 2001    90   3446     70   2     2   6    1
562     562         0          0 2001   112   2724     65   2     2   7    1
563     563         0          0 2001    98   1798     57   2     2   6    3
564     564         0          0 2001    98   1682     54   2     2   6    3
565     565         0          0 2001   220   9166     94   2     2   8    4
566     566         0          0 2001   125   2614     61   1     2   7    4
567     567         0          0 2001   228   1828     57   2     2   5    4
568     568         0          0 2001   180   2672     66   1     2   7    3
569     569         0          0 2001   180   1740     59   2     2   5    3
570     570         0          0 2001   180    564     38   2     2   3    3
571     571         0          0 2001   193   2508     63   2     2   6    3
572     572         0          0 2001   193   3472     70   2     2   6    3
573     573         0          0 2001   193   2496     64   2     2   7    3
574     574         0          0 2001   122   3018     65   2     2   7    3
575     575         0          0 2001   256   2082     60   2     2   5    3
576     576         0          0 2001   256   1714     56   2     2   7    3
577     577         0          0 2001   283   1316     49   2     2   6    2
578     578         0          0 2001   283   1114     46   2     2   6    2
579     579         0          0 2001   283   1790     55   2     2   7    2
580     580         0          0 2001   276   3206     71   2     2   7    2
581     581         0          0 2001   110   2128     59   2     2   4    2
582     582         0          0 2001   110   2240     62   2     2   5    2
583     583         0          0 2001   110   2092     60   2     2   4    2
584     584         0          0 2001   110   3652     72   2     2   5    2
585     585         0          0 2001   110   1828     55   2     2   4    2
586     586         0          0 2001   110   2138     59   2     2   6    2
587     587         0          0 2001   110   2224     63   2     2   4    2
588     588         0          0 2001   110   1784     56   1     2   4    2
589     589         0          0 2001   110   1480     56   1     2   4    2
590     590         0          0 2001   110   1908     56   2     2   5    2
591     591         0          0 2001   110   1472     50   2     2   4    2
592     592         0          0 2001    55   3702     69   2     4   6    1
593     593         0          0 2001    55   1550     53   2     4   5    1
594     594         0          0 2001    55   4070     75   1     4   8    1
595     595         0          0 2001    55   1896     58   2     4   7    1
596     596         0          0 2001    55   3658     71   2     4   8    1
597     597         0          0 2001    55   3762     74   2     4  10    1
598     598         0          0 2001    55   7270     90   1     4   8    1
599     599         0          0 2001    55   6934     93   2     4   8    1
600     600         0          0 2001    90   5108     82   1     4   9    1
601     601         0          0 2001    90   3948     72   2     4   6    1
602     602         0          0 2001    90   3042     69   2     4   6    1
603     603         0          0 2001   112   3266     72   1     4   7    1
604     604         0          0 2001   112   2230     63   2     4   7    1
605     605         0          0 2001   112   2552     63   2     4   5    1
606     606         0          0 2001   199   9990    101   2     4   9    2
607     607         0          0 2001   199   2988     70   1     4   5    2
608     608         0          0 2001   199   4180     82   1     4   7    2
609     609         0          0 2001   199   2828     72   2     4   7    2
610     610         0          0 2001   199   2956     67   1     4   5    2
611     611         0          0 2001   199   2580     69   1     4   7    2
612     612         0          0 2001   199   2682     66   1     4   5    2
613     613         0          0 2001   199     NA     NA   1     4   0    2
614     614         0          0 2001    98   4676     83   1     4   8    3
615     615         0          0 2001    98   4130     73   2     4   8    3
616     616         0          0 2001    98   2200     62   2     4   5    3
617     617         0          0 2001    98   7098     85   1     4   7    3
618     618         0          0 2001    98   3004     67   2     4   5    3
619     619         0          0 2001    98   5902     82   1     4   6    3
620     620         0          0 2001    98   4286     78   1     4   6    3
621     621         0          0 2001    98   4564     80   1     4   6    3
622     622         0          0 2001    98   1956     59   1     4   5    3
623     623         0          0 2001    98   2324     62   2     4   4    3
624     624         0          0 2001    98   2186     62   2     4   6    3
625     625         0          0 2001   125   7208     96   2     4   7    4
626     626         0          0 2001   125   2814     66   1     4   8    4
627     627         0          0 2001   125   3912     80   1     4   7    4
628     628         0          0 2001   125   2534     71   1     4   7    4
629     629         0          0 2001   140   2758     66   2     4   5    4
630     630         0          0 2001   140   1366     54   1     4   5    4
631     631         0          0 2001   140   2560     69   1     4   7    4
632     632         0          0 2001   228   7242     91   1     4   7    4
633     633         0          0 2001   228   4734     78   2     4   6    4
634     634         0          0 2001   228   4084     76   1     4   6    4
635     635         0          0 2001   228   5964     82   1     4   7    4
636     636         0          0 2001   193   6532     91   1     4   7    3
637     637         0          0 2001   193   7264     94   1     4   7    3
638     638         0          0 2001   122   8426     92   1     4  10    3
639     639         0          0 2001   122   4892     79   1     4   8    3
640     640         0          0 2001   122   3094     73   2     4   7    3
641     641         0          0 2001   122   5664     85   2     4   7    3
642     642         0          0 2001   122   3152     74   1     4   7    3
643     643         0          0 2001   122   2414     67   1     4   5    3
644     644         0          0 2001   122   3426     68   2     4   6    3
645     645         0          0 2001   122   3536     71   1     4   7    3
646     646         0          0 2001   122   2900     75   1     4   7    3
647     647         0          0 2001   256   3544     71   2     4   6    3
648     648         0          0 2001   256   3194     71   1     4   6    3
649     649         0          0 2001   256   8068     94   1     4  10    3
650     650         0          0 2001   256   3594     69   1     4   5    3
651     651         0          0 2001   283   2516     64   1     4   9    2
652     652         0          0 2001   283   3220     66   2     4   8    2
653     653         0          0 2001   283   1830     59   2     4   6    2
654     654         0          0 2001   110   3336     65   1     4   7    2
655     655         1          1 1999   194   2154     59   0     0   0    3
656     656         1          1 1999   194   1446     56   0     0   0    3
657     657         1          1 1999   194   4660     81   0     0   0    3
658     658         1          1 1999   235   1034     52   0     0   0    4
659     659         1          1 1999    85   1968     60   2     1   5    1
660     660         1          1 1999    85   1536     52   1     1   5    1
661     661         1          1 1999    85    376     36   1     1   2    1
662     662         1          1 1999    85   1070     48   1     1   3    1
663     663         1          1 1999    85    100     23   2     1   1    1
664     664         1          1 1999   137   3754     74   1     1   5    1
665     665         1          1 1999   137   2916     70   1     1   4    1
666     666         1          1 1999   150   1744     57   2     1   4    2
667     667         1          1 1999   150    558     37   1     1   2    2
668     668         1          1 1999   150   1572     54   1     1   5    2
669     669         1          1 1999   150    904     50   1     1   3    2
670     670         1          1 1999   100   1204     51   2     1   3    2
671     671         1          1 1999   220   1490     55   2     1   5    2
672     672         1          1 1999   220    362     35   2     1   3    2
673     673         1          1 1999   220    650     42   2     1   4    2
674     674         1          1 1999    99   1820     58   2     1   3    3
675     675         1          1 1999   270   1384     55   2     1   4    3
676     676         1          1 1999   270   1700     60   2     1   6    3
677     677         1          1 1999   270   1382     56   2     1   5    3
678     678         1          1 1999   270    826     45   2     1   3    3
679     679         1          1 1999   235    718     43   2     1   3    4
680     680         1          1 1999   235    766     43   2     1   3    4
681     681         1          1 1999   278    626     42   1     1   3    4
682     682         1          1 1999   200   2770     67   2     2   6    1
683     683         1          1 1999   200   4076     76   1     2   6    1
684     684         1          1 1999   200   2120     60   2     2   5    1
685     685         1          1 1999   200   1968     58   2     2   5    1
686     686         1          1 1999   200   1928     58   2     2   6    1
687     687         1          1 1999   200   7408     91   1     2  10    1
688     688         1          1 1999   292     NA     NA   1     2  10    2
689     689         1          1 1999    99   1256     50   1     2   4    3
690     690         1          1 1999    99   1754     57   2     2   5    3
691     691         1          1 1999   278   3452     73   2     2   5    4
692     692         1          1 1999   137   2168     60   1     4   5    1
693     693         2          1 1999   194   3442     72   0     0   0    3
694     694         2          1 1999   194   2248     59   0     0   0    3
695     695         2          1 1999    85   2606     65   1     1   5    1
696     696         2          1 1999    85    706     42   2     1   3    1
697     697         2          1 1999   200   2368     61   1     1   5    1
698     698         2          1 1999   200    984     48   2     1   4    1
699     699         2          1 1999   137   1568     55   2     1   4    1
700     700         2          1 1999   137    244     31   1     1   2    1
701     701         2          1 1999   292   1582     59   1     1   4    2
702     702         2          1 1999   292   2226     62   1     1   5    2
703     703         2          1 1999    99   1484     53   1     1   5    3
704     704         2          1 1999   270    808     47   2     1   4    3
705     705         2          1 1999   270    908     47   2     1   4    3
706     706         2          1 1999   270    928     48   2     1   4    3
707     707         2          1 1999   270    390     34   1     1   2    3
708     708         2          1 1999   256   1058     49   1     1   3    3
709     709         2          1 1999   172   1350     53   1     1   4    3
710     710         2          1 1999   172    236     31   2     1   2    3
711     711         2          1 1999   235   1244     55   1     1   4    4
712     712         2          1 1999   235   1320     55   2     1   4    4
713     713         2          1 1999   278   1938     60   2     1   5    4
714     714         2          1 1999   278   1882     65   2     1   5    4
715     715         2          1 1999   110   1174     52   2     1   4    4
716     716         2          1 1999   110   1306     53   1     1   4    4
717     717         2          1 1999   200   1866     58   2     2   5    1
718     718         2          1 1999   200   1924     57   1     2   5    1
719     719         2          1 1999   200   2126     63   1     2   6    1
720     720         2          1 1999   200   1876     57   2     2   5    1
721     721         2          1 1999   200   1512     52   2     2   4    1
722     722         2          1 1999   200   2608     64   1     2   6    1
723     723         2          1 1999   200   1886     56   2     2   5    1
724     724         2          1 1999   200   1438     53   2     2   5    1
725     725         2          1 1999   200   1772     55   2     2   5    1
726     726         3          1 1999   194   2012     59   0     0   0    3
727     727         3          1 1999   235    164     28   0     0   0    4
728     728         3          1 1999    85    476     38   1     1   2    1
729     729         3          1 1999    85   1626     52   1     1   4    1
730     730         3          1 1999    85    416     36   2     1   2    1
731     731         3          1 1999    85    290     31   2     1   2    1
732     732         3          1 1999    85    368     36   2     1   2    1
733     733         3          1 1999    85    296     32   2     1   2    1
734     734         3          1 1999   200    690     43   1     1   3    1
735     735         3          1 1999   137    682     42   1     1   3    1
736     736         3          1 1999   137   1988     60   1     1   4    1
737     737         3          1 1999   256   1294     53   2     1   3    3
738     738         3          1 1999   200   5400     83   1     2   6    1
739     739         3          1 1999   200   1632     55   1     2   5    1
740     740         3          1 1999   200   1970     60   1     2   5    1
741     741         3          1 1999   200   2408     64   2     2   6    1
742     742         3          1 1999   200     NA     NA   2     2  10    1
743     743         3          1 1999    99   3504     70   1     2   8    3
744     744         3          1 1999    99   1804     54   2     2   4    3
745     745         3          1 1999   137   4336     76   1     4   5    1
746     746         3          1 1999   137   3902     77   1     4   7    1
747     747         4          1 1999   235    508     39   0     0   0    4
748     748         4          1 1999    85    468     38   2     1   2    1
749     749         4          1 1999   137   1196     51   2     1   4    1
750     750         4          1 1999   220    630     42   2     1   2    2
751     751         4          1 1999   270   4562     81   1     1   8    3
752     752         4          1 1999   270    546     41   2     1   3    3
753     753         4          1 1999   256   1704     62   1     1   4    3
754     754         4          1 1999   256   2432     61   2     1   7    3
755     755         4          1 1999   256   1386     57   1     1   4    3
756     756         4          1 1999   278   1006     50   2     1   4    4
757     757         4          1 1999   278    172     29   2     1   2    4
758     758         4          1 1999   110    204     30   1     1   2    4
759     759         4          1 1999   110    444     39   2     1   3    4
760     760         4          1 1999    85   2144     60   2     2   5    1
761     761         4          1 1999   200   1410     57   1     2   5    1
762     762         4          1 1999   200   2620     65   2     2   6    1
763     763         4          1 1999   110   1714     55   2     2   4    4
764     764         5          1 1999   194   1698     55   0     0   0    3
765     765         5          1 1999   194   1998     62   0     0   0    3
766     766         5          1 1999   235    498     41   0     0   0    4
767     767         5          1 1999    85    776     43   1     1   3    1
768     768         5          1 1999   150   1446     55   1     1   4    2
769     769         5          1 1999   220   2100     64   1     1   5    2
770     770         5          1 1999   220   2072     61   1     1   5    2
771     771         5          1 1999   220   2184     62   2     1   5    2
772     772         5          1 1999   270   1570     54   2     1   5    3
773     773         5          1 1999   200   2632     62   2     2   6    1
774     774         5          1 1999   200   1782     56   1     2   5    1
775     775         5          1 1999   137   1318     49   2     2   5    1
776     776         6          1 1999    85    420     37   1     1   2    1
777     777         6          1 1999   200    296     32   1     1   2    1
778     778         6          1 1999   137   2282     64   1     1   5    1
779     779         6          1 1999   150   1902     62   1     1   5    2
780     780         6          1 1999   270   1636     58   1     1   5    3
781     781         6          1 1999   235   1998     59   1     1   4    4
782     782         6          1 1999   235    506     40   1     1   3    4
783     783         6          1 1999   278   1320     52   1     1   4    4
784     784         6          1 1999   200   1796     57   1     2   5    1
785     785         6          1 1999   200   2338     64   1     2   5    1
786     786         6          1 1999   200   1692     54   2     2   5    1
787     787         7          1 1999   235    562     42   0     0   0    4
788     788         7          1 1999    85   1994     56   1     1   4    1
789     789         7          1 1999   137   2476     64   1     1   5    1
790     790         7          1 1999   150   1200     52   2     1   4    2
791     791         7          1 1999   150   1350     54   1     1   4    2
792     792         7          1 1999   220   1706     59   1     1   4    2
793     793         7          1 1999   278   3056     74   1     1   6    4
794     794         7          1 1999   278    812     46   1     1   3    4
795     795         7          1 1999   278   1364     54   1     1   4    4
796     796         7          1 1999   137   7160     86   1     4  10    1
797     797         8          1 1999   137    296     33   2     1   2    1
798     798         8          1 1999   235    692     45   2     1   4    4
799     799         8          1 1999   200   1136     48   2     2   4    1
800     800         8          1 1999   220   1812     57   2     2   4    2
801     801         8          1 1999    99   2408     67   2     2   5    3
802     802         9          1 1999    85   1246     51   2     1   3    1
803     803         9          1 1999   270    762     48   1     1   4    3
804     804         9          1 1999   278   2818     68   1     1   5    4
805     805         9          1 1999   200   1948     60   1     2   5    1
806     806        10          1 1999   235    332     36   0     0   0    4
807     807        10          1 1999   200   3450     71   1     1   6    1
808     808        10          1 1999   235    670     42   1     1   3    4
809     809        10          1 1999   278    206     29   2     1   2    4
810     810        10          1 1999   200   2286     62   1     2   5    1
811     811        10          1 1999   200   1888     56   2     2   5    1
812     812        10          1 1999   137   1878     61   2     2   5    1
813     813        10          1 1999    99   2036     59   1     2   6    3
814     814        11          1 1999   235    898     49   0     0   0    4
815     815        11          1 1999   292   2066     64   1     1   6    2
816     816        11          1 1999   270    978     49   1     1   4    3
817     817        11          1 1999   200   1724     57   1     2   5    1
818     818        12          1 1999   194   1150     50   0     0   0    3
819     819        12          1 1999   137    252     30   1     1   0    1
820     820        12          1 1999   292   1164     54   2     1   4    2
821     821        12          1 1999   278    466     39   2     1   3    4
822     822        12          1 1999   278   2400     62   1     1   5    4
823     823        12          1 1999    85   1524     54   2     2   5    1
824     824        12          1 1999   200   1312     53   1     2   4    1
825     825        13          1 1999   137    916     47   2     1   3    1
826     826        13          1 1999   270    432     38   2     1   2    3
827     827        13          1 1999   110   1078     50   1     1   4    4
828     828        14          1 1999    85   2302     62   2     1   7    1
829     829        14          1 1999    99    958     47   1     1   3    3
830     830        14          1 1999   200   1484     53   2     2   5    1
831     831        14          1 1999   110   1264     52   2     2   4    4
832     832        15          1 1999   235   1094     50   2     1   4    4
833     833        15          1 1999   278    412     37   2     1   2    4
834     834        15          1 1999   270   1518     55   2     2   4    3
835     835        16          1 1999   235    946     47   2     1   3    4
836     836        16          1 1999   278    510     39   2     1   3    4
837     837        16          1 1999   200   2202     59   1     2   5    1
838     838        16          1 1999   110   2054     57   2     2   6    4
839     839        17          1 1999   137    624     40   1     1   3    1
840     840        17          1 1999   292   1826     62   1     1   5    2
841     841        17          1 1999   200   1892     59   2     2   5    1
842     842        17          1 1999   278   2072     58   2     2   5    4
843     843        18          1 1999   150   1954     60   2     1   5    2
844     844        18          1 1999   270    492     40   1     1   3    3
845     845        18          1 1999   235    708     43   1     1   3    4
846     846        19          1 1999   172    200     30   1     1   2    3
847     847        19          1 1999   200   1520     53   1     2   5    1
848     848        20          1 1999   200    842     46   1     1   3    1
849     849        20          1 1999   278    562     40   2     1   2    4
850     850        21          1 1999   256   1108     54   2     1   5    3
851     851        21          1 1999   278    198     29   1     1   2    4
852     852        21          1 1999   278   2034     58   2     2   4    4
853     853        22          1 1999   278    198     30   1     1   2    4
854     854        22          1 1999   200   1416     52   2     2   5    1
855     855        23          1 1999   235   1242     53   1     1   5    4
856     856        23          1 1999   235   1682     56   2     1   4    4
857     857        24          1 1999   235    932     49   0     0   0    4
858     858        25          1 1999   235   1126     49   0     0   0    4
859     859        25          1 1999   110   1238     49   2     2   4    4
860     860        26          1 1999   137   1582     56   2     1   5    1
861     861        27          1 1999   137   2566     68   1     1   4    1
862     862        28          1 1999   292    794     46   1     1   3    2
863     863        28          1 1999   235   1396     56   1     1   4    4
864     864        28          1 1999   235   1996     59   2     2   5    4
865     865        32          1 1999   270   1342     53   1     1   4    3
866     866        33          1 1999   278    382     37   1     1   2    4
867     867        35          1 1999   235    174     30   0     0   0    4
868     868        35          1 1999   235   1182     53   2     1   4    4
869     869        36          1 1999   292    680     45   1     1   3    2
870     870        38          1 1999   278    156     28   0     0   0    4
871     871        39          1 1999   235    714     44   0     0   0    4
872     872        41          1 1999   137    456     38   1     1   3    1
873     873        41          1 1999   200   2312     61   1     2   6    1
874     874        45          1 1999   278    154     27   0     0   0    4
875     875        50          1 1999   137   1284     51   2     1   5    1
876     876        51          1 1999   235    386     36   0     0   0    4
877     877        52          1 1999   200   1458     53   2     2   5    1
878     878        56          1 1999   235    664     43   0     0   0    4
879     879        65          1 1999   278    194     30   1     1   2    4
880     880        68          1 1999   235    320     34   0     0   0    4
881     881        73          1 1999   235    206     29   0     0   0    4
882     882        84          1 1999   150   1732     58   2     1   5    2
883     883        86          1 1999   278    178     28   2     1   2    4
884     884       126          1 1999   235   1248     52   1     1   4    4
885     885       160          1 1999   235    658     42   0     0   0    4
886     886       183          1 1999   235    236     30   0     0   0    4
887     887        NA          1 1999   194   3722     77   0     0   0    3
888     888        NA          1 1999   194   3594     70   0     0   0    3
889     889        NA          1 1999   194   1104     52   0     0   0    3
890     890        NA          1 1999   194   1368     54   0     0   0    3
891     891        NA          1 1999   194   1762     61   0     0   0    3
892     892        NA          1 1999   194   1240     52   0     0   0    3
893     893        NA          1 1999   194    668     42   0     0   0    3
894     894        NA          1 1999   194   2914     74   0     0   0    3
895     895        NA          1 1999   194   1756     55   0     0   0    3
896     896        NA          1 1999   194   1828     57   0     0   0    3
897     897        NA          1 1999   194   2720     66   0     0   0    3
898     898        NA          1 1999   194   1368     55   0     0   0    3
899     899        NA          1 1999   194   1834     60   0     0   0    3
900     900        NA          1 1999   194    420     36   0     0   0    3
901     901        NA          1 1999   194   2020     60   0     0   0    3
902     902        NA          1 1999   194   1886     61   0     0   0    3
903     903        NA          1 1999   194   3056     71   0     0   0    3
904     904        NA          1 1999   100   1744     61   2     1   6    2
905     905        NA          1 1999   100   1562     55   2     1   4    2
906     906        NA          1 1999   100   3002     68   1     1   5    2
907     907        NA          1 1999   100   1412     54   2     1   4    2
908     908        NA          1 1999   278   1320     50   1     1   4    4
909     909        NA          1 1999   278    332     36   1     1   2    4
910     910        NA          1 1999   278   1190     54   2     1   4    4
911     911        NA          1 1999   278    854     45   2     1   3    4
912     912        NA          1 1999   278   1140     50   2     1   4    4
913     913        NA          1 1999   278    984     49   2     1   4    4
914     914        NA          1 1999   278    652     42   1     1   4    4
915     915        NA          1 1999   278    580     42   2     1   3    4
916     916        NA          1 1999   278    476     39   1     1   3    4
917     917        NA          1 1999   278    360     35   2     1   2    4
918     918        NA          1 1999   110   1654     60   2     1   5    4
919     919        NA          1 1999   110   1786     61   1     1   5    4
920     920        NA          1 1999   110    912     48   1     1   3    4
921     921        NA          1 1999   110   2430     67   1     1   6    4
922     922        NA          1 1999   110    252     31   2     1   2    4
923     923        NA          1 1999   110    176     29   2     1   2    4
924     924        NA          1 1999   110   2136     62   1     1   5    4
925     925        NA          1 1999   110    916     49   2     1   3    4
926     926        NA          1 1999   110    526     39   2     1   3    4
927     927        NA          1 1999   110    354     36   2     1   3    4
928     928        NA          1 1999   110    418     36   1     1   3    4
929     929        NA          1 1999   110    356     35   1     1   3    4
930     930        NA          1 1999   110    670     42   2     1   3    4
931     931        NA          1 1999   110    816     45   2     1   3    4
932     932        NA          1 1999   110    324     35   1     1   2    4
933     933        NA          1 1999   110    234     32   2     1   2    4
934     934        NA          1 1999   110    206     31   2     1   2    4
935     935        NA          1 1999   278   2556     63   2     2   5    4
936     936        NA          1 1999   278   3172     68   1     2   6    4
937     937        NA          1 1999   278   2426     65   2     2   5    4
938     938        NA          1 1999   110   1380     52   1     2   5    4
939     939        NA          1 1999   110   1692     56   1     2   5    4
940     940        NA          1 1999   110   2160     60   1     2   5    4
941     941        NA          1 1999   110   1236     50   2     2   5    4
942     942        NA          1 1999   110   1608     53   2     2   5    4
943     943        NA          1 1999   110   1972     57   1     2   5    4
944     944         1          1 2000   121    950     49   1     1   3    1
945     945         1          1 2000   121   1672     62   1     1   5    1
946     946         1          1 2000   121   1280     51   1     1   3    1
947     947         1          1 2000   121   1278     52   1     1   4    1
948     948         1          1 2000   121   3836     78   1     1   6    1
949     949         1          1 2000   121   1072     51   1     1   6    1
950     950         1          1 2000   293   1908     62   1     1   5    2
951     951         1          1 2000   293   1034     51   2     1   3    2
952     952         1          1 2000   237   1548     59   2     1   6    2
953     953         1          1 2000   237    420     36   1     1   5    2
954     954         1          1 2000   285   1680     58   2     1   6    3
955     955         1          1 2000   285   1826     59   1     1   6    3
956     956         1          1 2000   285   2020     62   1     1   6    3
957     957         1          1 2000   285   1418     53   2     1   4    3
958     958         1          1 2000   285   1954     60   1     1   5    3
959     959         1          1 2000   285   1344     53   1     1   4    3
960     960         1          1 2000   285    954     49   2     1   3    3
961     961         1          1 2000   270    432     36   1     1   2    4
962     962         1          1 2000   260   1396     56   1     1   5    4
963     963         1          1 2000   121   2094     61   1     2   6    1
964     964         1          1 2000   121   3388     76   2     2   8    1
965     965         1          1 2000   102   2414     63   2     2   8    2
966     966         1          1 2000   293   4240     82   2     2   9    2
967     967         1          1 2000   237   3594     71   2     2   8    2
968     968         1          1 2000   285   2296     60   2     2   5    3
969     969         1          1 2000   285   2390     64   2     2   6    3
970     970         1          1 2000   285   2724     64   1     3   6    3
971     971         2          1 2000   121   1506     56   2     1   4    1
972     972         2          1 2000   121   6020     89   2     1   8    1
973     973         2          1 2000   102    940     45   2     1   3    2
974     974         2          1 2000   102   3892     69   2     1   7    2
975     975         2          1 2000   102    542     40   1     1   4    2
976     976         2          1 2000   285   2150     64   2     1   6    3
977     977         2          1 2000   285   1348     54   1     1   5    3
978     978         2          1 2000   285   1170     52   2     1   4    3
979     979         2          1 2000   270   2908     69   2     1   5    4
980     980         2          1 2000   270    554     40   2     1   3    4
981     981         2          1 2000   146    764     42   1     1   3    3
982     982         2          1 2000   121   2404     61   1     2   6    1
983     983         2          1 2000   121   2576     67   2     2   6    1
984     984         2          1 2000   121   2676     65   1     4   5    1
985     985         2          1 2000   146   2182     60   1     4   6    3
986     986         2          1 2000   146   1984     59   1     4   7    3
987     987         3          1 2000   121   2710     69   1     1   5    1
988     988         3          1 2000   102   1258     53   2     1   4    2
989     989         3          1 2000   285   2148     62   2     1   5    3
990     990         3          1 2000   285   3364     72   2     1   5    3
991     991         3          1 2000   270   3200     69   2     1   5    4
992     992         3          1 2000   260    990     51   1     1   5    4
993     993         3          1 2000   146   3258     73   1     1   7    3
994     994         3          1 2000   121   4310     74   1     2   6    1
995     995         3          1 2000   121   6600     92   1     2   7    1
996     996         3          1 2000   270   2162     60   2     2   7    4
997     997         3          1 2000   121   2582     61   2     3   5    1
998     998         3          1 2000   121   2778     62   1     4   6    1
999     999         3          1 2000   270   3152     69   1     4   6    4
1000   1000         3          1 2000   146   3200     66   2     4   7    3
1001   1001         3          1 2000   146   2236     64   1     4   4    3
1002   1002         4          1 2000   121   2234     63   1     1   5    1
1003   1003         4          1 2000   102    932     48   2     1   4    2
1004   1004         4          1 2000   237   1802     56   2     1   5    2
1005   1005         4          1 2000   237    870     47   2     1   4    2
1006   1006         4          1 2000   237   1660     55   1     1   4    2
1007   1007         4          1 2000   270   1748     58   2     1   4    4
1008   1008         4          1 2000   146   3372     72   2     1   5    3
1009   1009         4          1 2000   121   2160     59   1     2   6    1
1010   1010         4          1 2000   121   2736     62   1     2   5    1
1011   1011         4          1 2000   121   1286     52   2     2   6    1
1012   1012         4          1 2000   121   1652     55   1     4   6    1
1013   1013         4          1 2000   121   2032     59   1     4   6    1
1014   1014         4          1 2000   260   2804     68   1     4   5    4
1015   1015         5          1 2000   121    600     41   1     1   2    1
1016   1016         5          1 2000   285   3708     71   1     1   7    3
1017   1017         5          1 2000   270    472     38   2     1   3    4
1018   1018         5          1 2000   146   3622     78   2     1   8    3
1019   1019         5          1 2000   146    856     45   1     1   4    3
1020   1020         5          1 2000   121   2094     60   2     2   5    1
1021   1021         5          1 2000   121   4824     79   1     4   7    1
1022   1022         5          1 2000   260   3328     71   1     4   5    4
1023   1023         5          1 2000   146   2146     60   1     4   7    3
1024   1024         6          1 2000   102    902     45   2     1   3    2
1025   1025         6          1 2000   285   1052     51   2     1   4    3
1026   1026         6          1 2000   260    492     38   2     1   2    4
1027   1027         7          1 2000   260    828     46   1     1   3    4
1028   1028         7          1 2000   121   3012     66   2     2   6    1
1029   1029         7          1 2000   146   3002     70   1     4   5    3
1030   1030         8          1 2000   121    986     49   2     1   4    1
1031   1031         8          1 2000   121    988     49   1     1   4    1
1032   1032         8          1 2000   285   1952     60   1     1   5    3
1033   1033         8          1 2000   260   1936     58   2     1   4    4
1034   1034         8          1 2000   146    790     46   1     1   3    3
1035   1035         8          1 2000   146    682     43   2     1   3    3
1036   1036         8          1 2000   260   1712     55   2     2   4    4
1037   1037         8          1 2000   121   2762     65   1     4   6    1
1038   1038         9          1 2000   121   3040     70   1     1   6    1
1039   1039         9          1 2000   237   2490     66   1     1   8    2
1040   1040         9          1 2000   270    756     43   2     1   4    4
1041   1041        10          1 2000   121    726     43   1     1   3    1
1042   1042        10          1 2000   270    278     33   1     1   2    4
1043   1043        11          1 2000   260   1262     53   1     1   4    4
1044   1044        11          1 2000   260    442     35   2     1   3    4
1045   1045        12          1 2000   285    506     38   2     1   3    3
1046   1046        12          1 2000   285    686     44   2     1   3    3
1047   1047        12          1 2000   270    190     28   2     1   2    4
1048   1048        12          1 2000   260    444     35   1     1   3    4
1049   1049        13          1 2000   146    186     29   2     1   3    3
1050   1050        14          1 2000   260   2554     60   1     1   5    4
1051   1051        14          1 2000   121   2426     63   1     2   6    1
1052   1052        14          1 2000   121   2570     68   2     2   6    1
1053   1053        15          1 2000   121   1926     58   1     2   6    1
1054   1054        17          1 2000   260   2374     67   2     1   6    4
1055   1055        19          1 2000   121   1946     58   2     2   5    1
1056   1056        20          1 2000   121   1664     58   1     1   4    1
1057   1057        20          1 2000   260   2188     61   2     2   7    4
1058   1058        22          1 2000   270   1344     54   2     1   4    4
1059   1059        26          1 2000   285   1106     53   2     1   6    3
1060   1060        26          1 2000   270   1120     49   1     1   3    4
1061   1061        27          1 2000   270   1672     53   2     2   5    4
1062   1062        28          1 2000   260   2096     63   1     4   5    4
1063   1063        30          1 2000   260   3008     67   1     1   5    4
1064   1064        30          1 2000   260    418     38   2     1   4    4
1065   1065        30          1 2000   146    974     47   1     1   4    3
1066   1066        31          1 2000   146    700     43   2     1   3    3
1067   1067        31          1 2000   260   5658     80   1     2   6    4
1068   1068        35          1 2000   270   1304     51   2     1   4    4
1069   1069        39          1 2000   285   1430     57   2     1   6    3
1070   1070        40          1 2000   270   1432     53   1     1   5    4
1071   1071        43          1 2000   270    292     34   2     1   2    4
1072   1072        43          1 2000   146   6314     93   1     4   9    3
1073   1073        44          1 2000   270   1548     55   1     1   5    4
1074   1074        45          1 2000   285   1768     60   1     1   6    3
1075   1075        45          1 2000   260   1138     51   1     1   4    4
1076   1076        49          1 2000   270   1072     48   2     1   4    4
1077   1077        52          1 2000   270   1096     49   2     1   5    4
1078   1078        56          1 2000   146    198     29   2     1   2    3
1079   1079        56          1 2000   121   1488     54   2     2   5    1
1080   1080        58          1 2000   270    550     41   1     1   3    4
1081   1081        67          1 2000   102   1250     54   2     1   6    2
1082   1082        67          1 2000   260   2088     60   2     1   5    4
1083   1083        71          1 2000   146    234     30   2     1   2    3
1084   1084        81          1 2000   260    380     35   2     1   2    4
1085   1085       186          1 2000   146     92     22   1     1   1    3
1086   1086       210          1 2000   260    444     37   1     1   2    4
1087   1087       223          1 2000   270    434     36   2     1   3    4
1088   1088         1          1 2001    90   3754     72   1     1   5    1
1089   1089         1          1 2001   199   2472     67   2     1   6    2
1090   1090         1          1 2001   199    984     48   2     1   3    2
1091   1091         1          1 2001   199   2410     62   1     1   6    2
1092   1092         1          1 2001   199   3314     77   1     1   6    2
1093   1093         1          1 2001   199   1448     56   2     1   5    2
1094   1094         1          1 2001   199   3578     71   2     1   5    2
1095   1095         1          1 2001    98   1860     57   1     1   3    3
1096   1096         1          1 2001   220   3412     68   1     1   5    4
1097   1097         1          1 2001   125   2348     68   1     1   5    4
1098   1098         1          1 2001   125   3146     72   2     1   6    4
1099   1099         1          1 2001   140    836     46   1     1   3    4
1100   1100         1          1 2001   140    744     44   1     1   3    4
1101   1101         1          1 2001   140    620     43   2     1   3    4
1102   1102         1          1 2001   140    748     45   2     1   3    4
1103   1103         1          1 2001   140    938     51   1     1   3    4
1104   1104         1          1 2001   228   1558     58   1     1   5    4
1105   1105         1          1 2001   228    910     49   2     1   3    4
1106   1106         1          1 2001   228    600     40   1     1   3    4
1107   1107         1          1 2001   228   1104     52   1     1   4    4
1108   1108         1          1 2001   180   1940     59   1     1   5    3
1109   1109         1          1 2001   193   1266     56   2     1   5    3
1110   1110         1          1 2001   193    266     32   2     1   2    3
1111   1111         1          1 2001   193    414     35   2     1   2    3
1112   1112         1          1 2001   193    274     33   1     1   2    3
1113   1113         1          1 2001   122   1238     54   1     1   5    3
1114   1114         1          1 2001   122   1490     59   2     1   5    3
1115   1115         1          1 2001   122   1478     55   1     1   4    3
1116   1116         1          1 2001   122   2222     68   2     1   5    3
1117   1117         1          1 2001   122   2138     65   2     1   6    3
1118   1118         1          1 2001   122   1730     56   1     1   5    3
1119   1119         1          1 2001   256   1772     61   2     1   5    3
1120   1120         1          1 2001   276   1276     53   2     1   4    2
1121   1121         1          1 2001   276   2592     68   1     1   6    2
1122   1122         1          1 2001   256   2284     57   2     2   6    3
1123   1123         1          1 2001    98   1936     58   2     4   5    3
1124   1124         1          1 2001   125   6044     84   2     4   7    4
1125   1125         1          1 2001   125   6172     84   2     4   7    4
1126   1126         1          1 2001   140   5442     85   2     4   8    4
1127   1127         1          1 2001   140   4098     79   1     4   6    4
1128   1128         1          1 2001   140   3990     72   2     4   6    4
1129   1129         1          1 2001   256   1988     59   1     4   5    3
1130   1130         1          1 2001   276   5732     82   1     4   7    2
1131   1131         2          1 2001   112    252     29   2     1   2    1
1132   1132         2          1 2001   112    198     27   2     1   1    1
1133   1133         2          1 2001   199   3660     72   1     1   6    2
1134   1134         2          1 2001   199   1194     52   1     1   4    2
1135   1135         2          1 2001   220   1246     53   1     1   3    4
1136   1136         2          1 2001   125   1760     61   1     1   4    4
1137   1137         2          1 2001   228    570     42   1     1   3    4
1138   1138         2          1 2001   228    970     49   1     1   3    4
1139   1139         2          1 2001   193   1350     54   1     1   4    3
1140   1140         2          1 2001   122   2114     63   1     1   5    3
1141   1141         2          1 2001   122   1520     56   2     1   5    3
1142   1142         2          1 2001   256   1602     56   1     1   4    3
1143   1143         2          1 2001   256   1812     56   1     1   6    3
1144   1144         2          1 2001   260    968     49   1     1   3    2
1145   1145         2          1 2001   110    560     41   1     1   2    2
1146   1146         2          1 2001   110   1074     57   2     1   4    2
1147   1147         2          1 2001   140   2164     59   2     2   5    4
1148   1148         2          1 2001   125   4076     76   2     4   6    4
1149   1149         2          1 2001   140     NA     NA   1     4   9    4
1150   1150         2          1 2001   122   2192     60   2     4   7    3
1151   1151         2          1 2001   256   2808     65   1     4   6    3
1152   1152         2          1 2001   276   7888     94   2     4   9    2
1153   1153         3          1 2001   112    398     34   2     1   2    1
1154   1154         3          1 2001   140    748     44   1     1   3    4
1155   1155         3          1 2001   140    302     34   2     1   2    4
1156   1156         3          1 2001   140    366     34   1     1   2    4
1157   1157         3          1 2001   228    768     45   2     1   4    4
1158   1158         3          1 2001   228   1636     58   1     1   5    4
1159   1159         3          1 2001   228    596     41   2     1   3    4
1160   1160         3          1 2001   180    778     44   1     1   3    3
1161   1161         3          1 2001   193   1334     52   2     1   4    3
1162   1162         3          1 2001   283     66     19   2     1   1    2
1163   1163         3          1 2001   110   1738     65   2     1   4    2
1164   1164         3          1 2001   112   4432     80   1     4   7    1
1165   1165         3          1 2001   140   2154     63   1     4   5    4
1166   1166         3          1 2001   140   1994     61   2     4   5    4
1167   1167         3          1 2001   228   4938     81   2     4   7    4
1168   1168         3          1 2001   256   3412     74   1     4   5    3
1169   1169         4          1 2001   220   1094     52   1     1   4    4
1170   1170         4          1 2001   220   1042     50   2     1   5    4
1171   1171         4          1 2001   220   1588     58   1     1   4    4
1172   1172         4          1 2001   140    444     38   1     1   2    4
1173   1173         4          1 2001   140    760     44   1     1   4    4
1174   1174         4          1 2001   228    546     39   2     1   3    4
1175   1175         4          1 2001   180    886     50   2     1   5    3
1176   1176         4          1 2001   122   1060     49   1     1   4    3
1177   1177         4          1 2001   260   1476     55   2     1   4    2
1178   1178         4          1 2001   228   1820     56   2     2   5    4
1179   1179         4          1 2001   110   4494     78   2     2   6    2
1180   1180         4          1 2001   140   6478     92   1     4   9    4
1181   1181         4          1 2001   180   3074     64   2     4   7    3
1182   1182         4          1 2001   122   2286     63   1     4   7    3
1183   1183         5          1 2001   220   2556     60   1     1   5    4
1184   1184         5          1 2001   140    480     39   1     1   3    4
1185   1185         5          1 2001   228   3620     74   1     1   5    4
1186   1186         5          1 2001   228   1718     59   2     1   6    4
1187   1187         5          1 2001   122    636     44   2     1   3    3
1188   1188         5          1 2001   256   1938     64   2     1   6    3
1189   1189         5          1 2001   283   2650     65   1     1   5    2
1190   1190         5          1 2001   140   2306     60   2     2   7    4
1191   1191         5          1 2001   283   3244     71   2     2   6    2
1192   1192         5          1 2001   140   2604     63   1     4   8    4
1193   1193         6          1 2001   125   2056     63   1     1   4    4
1194   1194         6          1 2001   228    556     41   2     1   3    4
1195   1195         6          1 2001   122   1392     53   1     1   4    3
1196   1196         6          1 2001   276   1252     51   1     1   3    2
1197   1197         6          1 2001   276    366     36   2     1   3    2
1198   1198         6          1 2001   260   1594     53   2     2   4    2
1199   1199         6          1 2001   112   4286     78   2     4   6    1
1200   1200         6          1 2001   199   3716     78   2     4   7    2
1201   1201         7          1 2001   140   1014     47   1     1   4    4
1202   1202         7          1 2001   228    388     37   1     1   3    4
1203   1203         7          1 2001   276   2708     65   1     1   6    2
1204   1204         8          1 2001   199   2640     67   1     1   6    2
1205   1205         8          1 2001   228    416     38   1     1   4    4
1206   1206         8          1 2001   122   2754     70   1     1   6    3
1207   1207         8          1 2001   256   1360     54   1     1   4    3
1208   1208         8          1 2001   256    746     42   2     1   3    3
1209   1209         8          1 2001   110    786     45   1     1   3    2
1210   1210         8          1 2001   140   3398     67   1     2   7    4
1211   1211         8          1 2001   140   2952     67   2     2   6    4
1212   1212         9          1 2001   228   1688     62   2     1   5    4
1213   1213         9          1 2001   193    386     37   1     1   3    3
1214   1214         9          1 2001   283   2916     67   2     4   7    2
1215   1215        10          1 2001   140    504     39   2     1   2    4
1216   1216        10          1 2001   228    698     43   2     1   3    4
1217   1217        10          1 2001   228   2310     59   2     1   4    4
1218   1218        10          1 2001   228    798     46   2     1   3    4
1219   1219        10          1 2001   193    446     39   2     1   3    3
1220   1220        11          1 2001   256    902     49   2     1   4    3
1221   1221        13          1 2001   125   1828     64   2     1   6    4
1222   1222        13          1 2001   140    718     43   1     1   3    4
1223   1223        13          1 2001   228    382     37   2     1   3    4
1224   1224        14          1 2001   112    560     39   1     1   2    1
1225   1225        14          1 2001   256    444     36   2     1   3    3
1226   1226        14          1 2001   140   2602     65   1     4   7    4
1227   1227        16          1 2001   260   3566     71   1     4   7    2
1228   1228        17          1 2001   140   1542     55   2     1   4    4
1229   1229        17          1 2001   122    146     26   2     1   2    3
1230   1230        18          1 2001   228    692     42   2     1   3    4
1231   1231        18          1 2001   260    652     43   1     1   3    2
1232   1232        18          1 2001   256   2514     64   1     2   7    3
1233   1233        19          1 2001   260   2246     67   1     1   5    2
1234   1234        20          1 2001   228    244     31   1     1   2    4
1235   1235        20          1 2001   140   5900     84   1     4   9    4
1236   1236        30          1 2001   228   1004     48   2     1   3    4
1237   1237        34          1 2001   140   1408     52   2     2   6    4
1238   1238        36          1 2001   140   2052     60   2     2   6    4
1239   1239        40          1 2001   256   1962     61   2     1   5    3
1240   1240        42          1 2001   228    372     34   1     1   4    4
1241   1241        45          1 2001   256   1472     53   2     4   5    3
1242   1242        46          1 2001   220    660     43   1     1   3    4
1243   1243        46          1 2001   122    256     32   2     1   2    3
1244   1244        49          1 2001   140   1558     55   1     4   5    4
1245   1245        50          1 2001   228    484     38   2     1   3    4
1246   1246        55          1 2001   228    704     45   1     1   4    4
1247   1247        75          1 2001   140    884     46   2     1   3    4
1248   1248        84          1 2001   260    910     48   2     1   4    2
1249   1249        89          1 2001   260   1414     56   1     1   6    2
1250   1250        90          1 2001   228    224     31   1     1   2    4
1251   1251       104          1 2001   140    690     43   2     1   3    4
1252   1252       125          1 2001   140    754     44   2     1   3    4
1253   1253       128          1 2001   140   1270     55   2     4   7    4
1254   1254       257          1 2001   228    370     35   2     1   3    4
         WL2
1      19.24
2      18.72
3      19.71
4      17.94
5       3.40
6       6.80
7       4.94
8    1481.48
9     862.96
10    591.60
11    704.32
12    256.27
13    308.36
14    174.60
15    723.46
16    322.38
17   1268.77
18    694.85
19    655.49
20    769.42
21    660.02
22    505.02
23     96.33
24   1048.55
25    880.10
26    790.02
27    707.84
28   1010.75
29    687.58
30    666.60
31    743.38
32     64.40
33     52.02
34     55.65
35     44.16
36      9.24
37    238.76
38    419.76
39    372.35
40    394.68
41    352.41
42    453.20
43    345.27
44    504.90
45    337.08
46    340.00
47    210.60
48    453.75
49    398.56
50    241.92
51    206.08
52   1025.44
53     86.95
54     98.80
55     89.30
56    108.81
57   1045.84
58    437.76
59    574.80
60     51.20
61    282.24
62    346.68
63   1884.80
64    654.60
65    239.12
66     73.44
67     36.30
68    132.02
69    105.30
70     53.79
71     49.50
72     33.64
73    184.95
74    148.78
75     78.84
76     71.05
77     36.00
78     60.86
79     90.44
80    406.45
81    476.52
82    442.96
83     68.25
84    535.72
85   1380.24
86    575.94
87    832.92
88    505.04
89    570.72
90    884.48
91   1177.14
92    722.61
93    104.88
94    383.94
95    241.58
96     88.54
97     75.60
98     46.50
99    906.51
100   300.04
101   297.96
102   752.64
103   625.20
104   241.92
105  1449.05
106   477.95
107   189.90
108  1364.56
109   954.08
110   256.15
111   202.37
112   636.23
113   505.76
114   635.40
115   168.75
116   455.30
117    53.79
118  1652.42
119    33.00
120    41.92
121    25.76
122    25.20
123   234.24
124   349.44
125   980.21
126   111.52
127   170.28
128    83.62
129    41.28
130    27.55
131    42.56
132    28.42
133   544.57
134   347.68
135  1205.23
136   314.50
137   526.68
138   317.73
139   601.21
140  1824.13
141   318.24
142   257.28
143   196.42
144   672.08
145   277.00
146   280.50
147   625.25
148   297.84
149   353.51
150   226.54
151   138.99
152   263.62
153   321.88
154   528.96
155   189.20
156   315.00
157   300.04
158   201.24
159   439.45
160   812.50
161   572.89
162   180.95
163   107.60
164  1506.18
165   210.72
166   395.45
167   469.64
168   331.25
169   312.63
170   351.39
171   270.48
172   624.33
173   793.60
174   291.21
175    95.16
176   380.05
177   505.63
178   169.65
179   493.49
180   679.04
181   114.76
182   903.50
183   741.76
184   356.16
185   502.20
186   303.16
187   268.26
188   579.69
189   141.54
190   202.57
191   122.40
192   808.96
193   416.90
194   212.91
195    82.46
196    26.39
197    35.65
198    29.00
199    32.19
200    35.70
201    24.64
202    29.70
203    24.36
204    23.80
205    30.60
206   848.64
207   299.50
208  1379.25
209   259.00
210  1057.77
211   116.40
212   236.64
213   145.64
214    44.55
215   240.10
216   345.80
217    65.52
218  1084.60
219   131.46
220   181.24
221   246.84
222   356.94
223   378.00
224   226.08
225   292.56
226   100.00
227    48.84
228    24.36
229    66.60
230   409.16
231   402.80
232   554.48
233   280.28
234   375.36
235   361.59
236   325.85
237   222.78
238   744.90
239   807.03
240   469.70
241   459.25
242   495.90
243   742.76
244  1184.56
245   926.72
246   470.80
247   506.73
248   495.00
249  1573.11
250   505.02
251   663.40
252   273.42
253   516.32
254   342.72
255   299.70
256   701.82
257   540.56
258   322.83
259   265.09
260   931.77
261  1055.34
262   759.45
263  1266.30
264  1031.56
265   695.64
266   482.35
267    24.92
268   426.06
269   628.35
270   326.00
271  1516.26
272  2811.60
273  3534.30
274     0.00
275  2973.88
276   968.50
277  1446.48
278   803.88
279   375.87
280   458.28
281   195.05
282   238.08
283   110.40
284   505.76
285   140.28
286    80.64
287    73.80
288   311.61
289   415.26
290   874.20
291   273.42
292  1521.75
293   108.80
294    69.65
295   100.23
296   269.76
297   249.12
298   389.55
299  1630.50
300    79.20
301   585.28
302   599.63
303   268.03
304   226.78
305  1196.35
306   211.60
307   790.02
308   231.71
309   505.04
310    98.67
311   185.68
312    45.26
313   354.64
314   264.00
315   488.88
316  1392.93
317   425.15
318  1185.80
319   365.20
320    60.86
321   370.15
322  1777.50
323   608.17
324   218.55
325    86.26
326   491.26
327   383.35
328   225.89
329   680.76
330   511.53
331   242.32
332  1489.60
333   385.32
334   634.84
335   411.04
336   834.15
337   323.83
338    31.20
339   386.10
340   697.97
341   174.68
342    51.81
343    86.64
344   104.14
345   957.43
346    35.67
347    44.16
348   349.35
349   965.47
350   585.00
351   764.82
352   437.94
353  1892.16
354  1606.64
355  1158.51
356   723.84
357  1776.71
358  1707.09
359  2135.64
360     0.00
361   563.92
362  1733.60
363   537.51
364  2934.75
365     2.89
366   183.61
367   546.36
368   339.66
369   486.75
370   546.06
371   378.95
372   286.50
373   519.84
374   287.63
375   323.40
376   312.63
377   545.40
378   224.66
379    60.39
380    41.70
381    41.85
382   241.11
383   283.71
384    61.95
385   220.34
386    41.54
387   115.20
388   652.20
389    90.00
390   192.60
391   128.00
392    22.36
393    68.60
394    55.42
395    26.32
396    30.80
397    22.10
398  1003.68
399   686.07
400   182.83
401   437.36
402   164.26
403   400.95
404   658.98
405   237.16
406   249.60
407  1038.50
408    64.01
409    97.66
410  1072.36
411   345.27
412  1119.67
413   499.14
414   203.78
415    94.38
416    38.72
417   355.32
418   776.16
419   504.45
420   176.30
421   432.88
422   559.20
423   617.14
424   966.14
425   399.09
426   282.73
427   486.00
428   352.56
429   400.14
430   290.57
431   418.55
432   412.56
433   122.00
434   631.78
435   212.52
436    72.72
437   251.37
438   282.54
439   387.43
440   395.82
441   418.88
442   438.48
443   503.40
444   540.02
445   767.65
446   657.72
447   271.46
448   254.80
449   172.80
450   191.36
451   381.70
452   246.72
453   129.97
454    96.52
455  1099.08
456   817.08
457   195.51
458   139.32
459   111.11
460    88.14
461    60.52
462    29.29
463    28.13
464    13.20
465    10.81
466    16.90
467     4.94
468     3.40
469     4.14
470   372.32
471   706.80
472   319.28
473   103.36
474   144.06
475    91.08
476   162.97
477   339.00
478   233.59
479   434.16
480   238.29
481   111.15
482   156.20
483  1006.07
484   625.58
485   497.61
486   842.16
487   197.40
488    37.20
489    16.50
490    30.74
491    18.50
492    20.52
493  1213.92
494   786.76
495   512.40
496   343.44
497   190.08
498   792.66
499   437.80
500   616.14
501   238.76
502    30.16
503    17.50
504   362.88
505   572.18
506   149.21
507    22.14
508     4.14
509     3.23
510  1000.31
511   216.00
512   322.40
513   196.88
514   249.60
515    91.58
516   905.28
517   174.60
518   179.52
519   796.25
520   421.85
521   726.02
522   434.16
523   769.36
524    70.92
525    95.38
526   847.98
527   339.08
528   342.38
529   230.77
530  1242.46
531    63.00
532    92.04
533    20.02
534   357.76
535   789.88
536   435.78
537   350.37
538   409.32
539   221.76
540   801.99
541   368.16
542    73.50
543   265.68
544   276.85
545  1231.10
546   647.40
547   466.02
548   502.17
549   316.20
550   438.35
551   300.90
552   315.18
553   220.00
554   752.22
555   460.08
556   302.82
557   372.59
558   412.50
559   375.30
560   363.58
561  1206.10
562   885.30
563   512.43
564   454.14
565  4308.02
566   797.27
567   520.98
568   881.76
569   513.30
570   107.16
571   790.02
572  1215.20
573   798.72
574   980.85
575   624.60
576   479.92
577   322.42
578   256.22
579   492.25
580  1138.13
581   627.76
582   694.40
583   627.60
584  1314.72
585   502.70
586   630.71
587   700.56
588   499.52
589   414.40
590   534.24
591   368.00
592  1277.19
593   410.75
594  1526.25
595   549.84
596  1298.59
597  1391.94
598  3271.50
599  3224.31
600  2094.28
601  1421.28
602  1049.49
603  1175.76
604   702.45
605   803.88
606  5044.95
607  1045.80
608  1713.80
609  1018.08
610   990.26
611   890.10
612   885.06
613     0.00
614  1940.54
615  1507.45
616   682.00
617  3016.65
618  1006.34
619  2419.82
620  1671.54
621  1825.60
622   577.02
623   720.44
624   677.66
625  3459.84
626   928.62
627  1564.80
628   899.57
629   910.14
630   368.82
631   883.20
632  3295.11
633  1846.26
634  1551.92
635  2445.24
636  2972.06
637  3414.08
638  3875.96
639  1932.34
640  1129.31
641  2407.20
642  1166.24
643   808.69
644  1164.84
645  1255.28
646  1087.50
647  1258.12
648  1133.87
649  3791.96
650  1239.93
651   805.12
652  1062.60
653   539.85
654  1084.20
655   635.43
656   404.88
657  1887.30
658   268.84
659   590.40
660   399.36
661    67.68
662   256.80
663    11.50
664  1388.98
665  1020.60
666   497.04
667   103.23
668   424.44
669   226.00
670   307.02
671   409.75
672    63.35
673   136.50
674   527.80
675   380.60
676   510.00
677   386.96
678   185.85
679   154.37
680   164.69
681   131.46
682   927.95
683  1548.88
684   636.00
685   570.72
686   559.12
687  3370.64
688     0.00
689   314.00
690   499.89
691  1259.98
692   650.40
693  1239.12
694   663.16
695   846.95
696   148.26
697   722.24
698   236.16
699   431.20
700    37.82
701   466.69
702   690.06
703   393.26
704   189.88
705   213.38
706   222.72
707    66.30
708   259.21
709   357.75
710    36.58
711   342.10
712   363.00
713   581.40
714   611.65
715   305.24
716   346.09
717   541.14
718   548.34
719   669.69
720   534.66
721   393.12
722   834.56
723   528.08
724   381.07
725   487.30
726   593.54
727    22.96
728    90.44
729   422.76
730    74.88
731    44.95
732    66.24
733    47.36
734   148.35
735   143.22
736   596.40
737   342.91
738  2241.00
739   448.80
740   591.00
741   770.56
742     0.00
743  1226.40
744   487.08
745  1647.68
746  1502.27
747    99.06
748    88.92
749   304.98
750   132.30
751  1847.61
752   111.93
753   528.24
754   741.76
755   395.01
756   251.50
757    24.94
758    30.60
759    86.58
760   643.20
761   401.85
762   851.50
763   471.35
764   466.95
765   619.38
766   102.09
767   166.84
768   397.65
769   672.00
770   631.96
771   677.04
772   423.90
773   815.92
774   498.96
775   322.91
776    77.70
777    47.36
778   730.24
779   589.62
780   474.44
781   589.41
782   101.20
783   343.20
784   511.86
785   748.16
786   456.84
787   118.02
788   558.32
789   792.32
790   312.00
791   364.50
792   503.27
793  1130.72
794   186.76
795   368.28
796  3078.80
797    48.84
798   155.70
799   272.64
800   516.42
801   806.68
802   317.73
803   182.88
804   958.12
805   584.40
806    59.76
807  1224.75
808   140.70
809    29.87
810   708.66
811   528.64
812   572.79
813   600.62
814   220.01
815   661.12
816   239.61
817   491.34
818   287.50
819    37.80
820   314.28
821    90.87
822   744.00
823   411.48
824   347.68
825   215.26
826    82.08
827   269.50
828   713.62
829   225.13
830   393.26
831   328.64
832   273.50
833    76.22
834   417.45
835   222.31
836    99.45
837   649.59
838   585.39
839   124.80
840   566.06
841   558.14
842   600.88
843   586.20
844    98.40
845   152.22
846    30.00
847   402.80
848   193.66
849   112.40
850   299.16
851    28.71
852   589.86
853    29.70
854   368.16
855   329.13
856   470.96
857   228.34
858   275.87
859   303.31
860   442.96
861   872.44
862   182.62
863   390.88
864   588.82
865   355.63
866    70.67
867    26.10
868   313.23
869   153.00
870    21.84
871   157.08
872    86.64
873   705.16
874    20.79
875   327.42
876    69.48
877   386.37
878   142.76
879    29.10
880    54.40
881    29.87
882   502.28
883    24.92
884   324.48
885   138.18
886    35.40
887  1432.97
888  1257.90
889   287.04
890   369.36
891   537.41
892   322.40
893   140.28
894  1078.18
895   482.90
896   520.98
897   897.60
898   376.20
899   550.20
900    75.60
901   606.00
902   575.23
903  1084.88
904   531.92
905   429.55
906  1020.68
907   381.24
908   330.00
909    59.76
910   321.30
911   192.15
912   285.00
913   241.08
914   136.92
915   121.80
916    92.82
917    63.00
918   496.20
919   544.73
920   218.88
921   814.05
922    39.06
923    25.52
924   662.16
925   224.42
926   102.57
927    63.72
928    75.24
929    62.30
930   140.70
931   183.60
932    56.70
933    37.44
934    31.93
935   805.14
936  1078.48
937   788.45
938   358.80
939   473.76
940   648.00
941   309.00
942   426.12
943   562.02
944   232.75
945   518.32
946   326.40
947   332.28
948  1496.04
949   273.36
950   591.48
951   263.67
952   456.66
953    75.60
954   487.20
955   538.67
956   626.20
957   375.77
958   586.20
959   356.16
960   233.73
961    77.76
962   390.88
963   638.67
964  1287.44
965   760.41
966  1738.40
967  1275.87
968   688.80
969   764.80
970   871.68
971   421.68
972  2678.90
973   211.50
974  1342.74
975   108.40
976   688.00
977   363.96
978   304.20
979  1003.26
980   110.80
981   160.44
982   733.22
983   862.96
984   869.70
985   654.60
986   585.28
987   934.95
988   333.37
989   665.88
990  1211.04
991  1104.00
992   252.45
993  1189.17
994  1594.70
995  3036.00
996   648.60
997   787.51
998   861.18
999  1087.44
1000 1056.00
1001  715.52
1002  703.71
1003  223.68
1004  504.56
1005  204.45
1006  456.50
1007  506.92
1008 1213.92
1009  637.20
1010  848.16
1011  334.36
1012  454.30
1013  599.44
1014  953.36
1015  123.00
1016 1316.34
1017   89.68
1018 1412.58
1019  192.60
1020  628.20
1021 1905.48
1022 1181.44
1023  643.80
1024  202.95
1025  268.26
1026   93.48
1027  190.44
1028  993.96
1029 1050.70
1030  241.57
1031  242.06
1032  585.60
1033  561.44
1034  181.70
1035  146.63
1036  470.80
1037  897.65
1038 1064.00
1039  821.70
1040  162.54
1041  156.09
1042   45.87
1043  334.43
1044   77.35
1045   96.14
1046  150.92
1047   26.60
1048   77.70
1049   26.97
1050  766.20
1051  764.19
1052  873.80
1053  558.54
1054  795.29
1055  564.34
1056  482.56
1057  667.34
1058  362.88
1059  293.09
1060  274.40
1061  443.08
1062  660.24
1063 1007.68
1064   79.42
1065  228.89
1066  150.50
1067 2263.20
1068  332.52
1069  407.55
1070  379.48
1071   49.64
1072 2936.01
1073  425.70
1074  530.40
1075  290.19
1076  257.28
1077  268.52
1078   28.71
1079  401.76
1080  112.75
1081  337.50
1082  626.40
1083   35.10
1084   66.50
1085   10.12
1086   82.14
1087   78.12
1088 1351.44
1089  828.12
1090  236.16
1091  747.10
1092 1275.89
1093  405.44
1094 1270.19
1095  530.10
1096 1160.08
1097  798.32
1098 1132.56
1099  192.28
1100  163.68
1101  133.30
1102  168.30
1103  239.19
1104  451.82
1105  222.95
1106  120.00
1107  287.04
1108  572.30
1109  354.48
1110   42.56
1111   72.45
1112   45.21
1113  334.26
1114  439.55
1115  406.45
1116  755.48
1117  694.85
1118  484.40
1119  540.46
1120  338.14
1121  881.28
1122  650.94
1123  561.44
1124 2538.48
1125 2592.24
1126 2312.85
1127 1618.71
1128 1436.40
1129  586.46
1130 2350.12
1131   36.54
1132   26.73
1133 1317.60
1134  310.44
1135  330.19
1136  536.80
1137  119.70
1138  237.65
1139  364.50
1140  665.91
1141  425.60
1142  448.56
1143  507.36
1144  237.16
1145  114.80
1146  306.09
1147  638.38
1148 1548.88
1149    0.00
1150  657.60
1151  912.60
1152 3707.36
1153   67.66
1154  164.56
1155   51.34
1156   62.22
1157  172.80
1158  474.44
1159  122.18
1160  171.16
1161  346.84
1162    6.27
1163  564.85
1164 1772.80
1165  678.51
1166  608.17
1167 1999.89
1168 1262.44
1169  284.44
1170  260.50
1171  460.52
1172   84.36
1173  167.20
1174  106.47
1175  221.50
1176  259.70
1177  405.90
1178  509.60
1179 1752.66
1180 2979.88
1181  983.68
1182  720.09
1183  766.80
1184   93.60
1185 1339.40
1186  506.81
1187  139.92
1188  620.16
1189  861.25
1190  691.80
1191 1151.62
1192  820.26
1193  647.64
1194  113.98
1195  368.88
1196  319.26
1197   65.88
1198  422.41
1199 1671.54
1200 1449.24
1201  238.29
1202   71.78
1203  880.10
1204  884.40
1205   79.04
1206  963.90
1207  367.20
1208  156.66
1209  176.85
1210 1138.33
1211  988.92
1212  523.28
1213   71.41
1214  976.86
1215   98.28
1216  150.07
1217  681.45
1218  183.54
1219   86.97
1220  220.99
1221  584.96
1222  154.37
1223   70.67
1224  109.20
1225   79.92
1226  845.65
1227 1265.93
1228  424.05
1229   18.98
1230  145.32
1231  140.18
1232  804.48
1233  752.41
1234   37.82
1235 2478.00
1236  240.96
1237  366.08
1238  615.60
1239  598.41
1240   63.24
1241  390.08
1242  141.90
1243   40.96
1244  428.45
1245   91.96
1246  158.40
1247  203.32
1248  218.40
1249  395.92
1250   34.72
1251  148.35
1252  165.88
1253  349.25
1254   64.75</code></pre>
</div>
</div>
</section>
<section id="model-1" class="slide level2">
<h2>Model</h2>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
glm(formula = Prevalence ~ Length + Year + Area, family = binomial(link = "logit"), 
    data = cod)

Coefficients:
             Estimate Std. Error z value Pr(&gt;|z|)    
(Intercept) -0.465947   0.269333  -1.730 0.083629 .  
Length       0.009654   0.004468   2.161 0.030705 *  
Year2000     0.566536   0.169715   3.338 0.000843 ***
Year2001    -0.680315   0.140175  -4.853 1.21e-06 ***
Area2       -0.626192   0.186617  -3.355 0.000792 ***
Area3       -0.510470   0.163396  -3.124 0.001783 ** 
Area4        1.233878   0.184652   6.682 2.35e-11 ***
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

(Dispersion parameter for binomial family taken to be 1)

    Null deviance: 1727.8  on 1247  degrees of freedom
Residual deviance: 1537.6  on 1241  degrees of freedom
  (6 observations deleted due to missingness)
AIC: 1551.6

Number of Fisher Scoring iterations: 4</code></pre>
</div>
</div>
<p>These are all from a linear model. Need to transform them to get the real value in probabilistic scale</p>
<p>Additive! One slope</p>
</section>
<section id="how-to-estimate-the-values" class="slide level2">
<h2>How to estimate the values?</h2>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
glm(formula = Prevalence ~ Length + Year + Area, family = binomial(link = "logit"), 
    data = cod)

Coefficients:
             Estimate Std. Error z value Pr(&gt;|z|)    
(Intercept) -0.465947   0.269333  -1.730 0.083629 .  
Length       0.009654   0.004468   2.161 0.030705 *  
Year2000     0.566536   0.169715   3.338 0.000843 ***
Year2001    -0.680315   0.140175  -4.853 1.21e-06 ***
Area2       -0.626192   0.186617  -3.355 0.000792 ***
Area3       -0.510470   0.163396  -3.124 0.001783 ** 
Area4        1.233878   0.184652   6.682 2.35e-11 ***
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

(Dispersion parameter for binomial family taken to be 1)

    Null deviance: 1727.8  on 1247  degrees of freedom
Residual deviance: 1537.6  on 1241  degrees of freedom
  (6 observations deleted due to missingness)
AIC: 1551.6

Number of Fisher Scoring iterations: 4</code></pre>
</div>
</div>
<p><span class="math display">\[
logistic(\pi_i)  = \beta_0 + \beta_1 x_{1,i}+ \beta_2 x_{2,i} + \beta_3 x_{3,i}+ \beta_4 x_{4,i} + \beta_5 x_{5,i} + \beta_6 x_{6,i}
\]</span></p>
<p>Site</p>
<table class="caption-top" style="width:100%;">
<colgroup>
<col style="width: 14%">
<col style="width: 14%">
<col style="width: 14%">
<col style="width: 14%">
<col style="width: 14%">
<col style="width: 14%">
<col style="width: 14%">
</colgroup>
<thead>
<tr class="header">
<th></th>
<th>Value of <span class="math inline">\(x_2\)</span></th>
<th>Value of <span class="math inline">\(x_3\)</span></th>
<th>Value of <span class="math inline">\(x_4\)</span></th>
<th>Value of <span class="math inline">\(x_5\)</span></th>
<th>Value of <span class="math inline">\(x_6\)</span></th>
<th>Value of <span class="math inline">\(x_7\)</span></th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td></td>
<td>2000</td>
<td>2001</td>
<td>Area 1</td>
<td>Area 2</td>
<td>Area 3</td>
<td>Area 4</td>
</tr>
<tr class="even">
<td>Area-1 1999</td>
<td>0</td>
<td>0</td>
<td>0</td>
<td>0</td>
<td>0</td>
<td>0</td>
</tr>
<tr class="odd">
<td>Area-1 2000</td>
<td>1</td>
<td>0</td>
<td>0</td>
<td>0</td>
<td>0</td>
<td>0</td>
</tr>
<tr class="even">
<td>Area-1 2001</td>
<td>0</td>
<td>1</td>
<td>0</td>
<td>0</td>
<td>0</td>
<td>0</td>
</tr>
<tr class="odd">
<td>Area-2 1999</td>
<td>0</td>
<td>0</td>
<td>0</td>
<td>1</td>
<td>0</td>
<td>0</td>
</tr>
<tr class="even">
<td>Area-2 2000</td>
<td>0</td>
<td>1</td>
<td>0</td>
<td>1</td>
<td>0</td>
<td>0</td>
</tr>
<tr class="odd">
<td>Area-2 2001</td>
<td>0</td>
<td>0</td>
<td>1</td>
<td>1</td>
<td>0</td>
<td>0</td>
</tr>
<tr class="even">
<td>Area 3- 1999</td>
<td>0</td>
<td>0</td>
<td>0</td>
<td>0</td>
<td>1</td>
<td>0</td>
</tr>
<tr class="odd">
<td>Area 3 -2000</td>
<td>1</td>
<td>0</td>
<td>0</td>
<td>0</td>
<td>1</td>
<td>0</td>
</tr>
<tr class="even">
<td>Area 3 - 2001</td>
<td>0</td>
<td>1</td>
<td>0</td>
<td>0</td>
<td>1</td>
<td>0</td>
</tr>
<tr class="odd">
<td>Area 4 - 1999</td>
<td>0</td>
<td>0</td>
<td>0</td>
<td>0</td>
<td>0</td>
<td>1</td>
</tr>
<tr class="even">
<td>Area 4 - 2000</td>
<td>0</td>
<td>1</td>
<td>0</td>
<td>0</td>
<td>0</td>
<td>1</td>
</tr>
<tr class="odd">
<td>Area 4 2001</td>
<td>0</td>
<td>0</td>
<td>1</td>
<td>0</td>
<td>0</td>
<td>1</td>
</tr>
</tbody>
</table>
</section>
<section id="categorical" class="slide level2">
<h2>Categorical</h2>

<img data-src="images/clipboard-1773874490.png" class="r-stretch"></section>
<section id="section" class="slide level2">
<h2></h2>

<img data-src="images/clipboard-2685946074.png" class="r-stretch"></section>
<section id="section-1" class="slide level2">
<h2></h2>

<img data-src="images/clipboard-2466917050.png" class="r-stretch"></section>
<section id="this-weeks-lab" class="slide level2">
<h2>This week’s lab</h2>
<ul>
<li class="fragment"><p>Create your own assignment</p></li>
<li class="fragment"><p>I have been reviewing assignments, and I will meet with some of you to go over some concepts</p></li>
<li class="fragment"><p>Next week: repeated measures, pseudoreplication, mixed models</p></li>
</ul>
</section>
<section id="section-2" class="slide level2">
<h2></h2>
</section>
<section id="logistic-regression-assumptions" class="slide level2">
<h2>Logistic regression assumptions</h2>
<ul>
<li class="fragment"><p>Binomial distribution</p></li>
<li class="fragment"><p>Binary data (1, 0)</p></li>
</ul>
</section>
<section id="poisson-assumptions" class="slide level2">
<h2>Poisson assumptions</h2>
<ul>
<li class="fragment"><p>We have talked about count-data</p></li>
<li class="fragment"><p>While we usually think Poisson, it has an important assumption: <span class="math inline">\(Var(y_i) = \lambda\_i\)</span></p></li>
</ul>

<img data-src="images/clipboard-202474714.png" class="r-stretch"></section>
<section id="how-to-check-for-overdispersion" class="slide level2">
<h2>How to check for overdispersion?</h2>
<p>Package: performance</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb14"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb14-1"><a href=""></a> performance<span class="sc">::</span><span class="fu">check_overdispersion</span>(model)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
</section>
<section id="what-to-do-when-there-is-overdispersion" class="slide level2">
<h2>What to do when there is overdispersion?</h2>
<p><strong>I have never encountered non-overdispersed count data!</strong></p>
<p>So, what to do?</p>
<ul>
<li class="fragment"><p>Add more covariates</p></li>
<li class="fragment"><p>Make a mixed effects model</p></li>
<li class="fragment"><p>Zero inflated models!</p></li>
</ul>
<div class="cell">
<div class="sourceCode cell-code" id="cb15"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb15-1"><a href=""></a>performance<span class="sc">::</span><span class="fu">check_zeroinflation</span>(fit.pr)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
</section>
<section id="what-to-do-when-there-is-overdispersion-1" class="slide level2">
<h2>What to do when there is overdispersion?</h2>
<p>If we suspect zero inflation, we have several options for zero inflated models</p>
<ul>
<li class="fragment"><p>Negative binomial regression</p></li>
<li class="fragment"><p>Hurdle models</p></li>
<li class="fragment"><p>Zero-inflated mixture model (mixed-effects)</p></li>
</ul>
</section>
<section id="glms-other-assumptions" class="slide level2">
<h2>GLM’s other assumptions</h2>
<ul>
<li class="fragment"><p>Data is independently distributed</p></li>
<li class="fragment"><p>Error is independent</p></li>
</ul>
</section>
<section id="next-classes" class="slide level2">
<h2>Next classes</h2>
<ul>
<li class="fragment"><p>Mixed effects models</p></li>
<li class="fragment"><p>Repeated measures</p></li>
<li class="fragment"><p>zero inflation</p></li>
<li class="fragment"><p>Other models</p></li>
</ul>
</section>
<section id="question-1" class="slide level2">
<h2>Question 1</h2>
<p>Interested in the concentration of mercury in Lake Michigan</p>

<img data-src="images/clipboard-3586888397.png" class="r-stretch"><ul>
<li class="fragment"><p>We use code to randomly select 4 sites</p></li>
<li class="fragment"><p>At each site we set up a net</p></li>
<li class="fragment"><p>Return later and test Hg concentration of each fish</p></li>
</ul>
</section>
<section id="question-1-1" class="slide level2">
<h2>Question 1:</h2>
<ul>
<li class="fragment"><p>What is the experimental unit?</p></li>
<li class="fragment"><p>What is the response variable?</p></li>
<li class="fragment"><p>Where is sampling coming from or being introduced?</p></li>
<li class="fragment"><div>
<p><img data-src="images/clipboard-859519992.png"></p>
</div></li>
<li class="fragment"><p>What do we care about?</p></li>
</ul>
</section>
<section id="question-2" class="slide level2">
<h2>Question 2:</h2>
<ul>
<li class="fragment"><p>We are testing infection prevalence in turkeys 🦃</p></li>
<li class="fragment"><p>We trap multiple individuals from a flock, and test them all 🦃</p></li>
<li class="fragment"><p>We do this for multiple flocks</p></li>
<li class="fragment"><p>What is introducing variance?</p></li>
</ul>
</section>
<section id="question-3" class="slide level2">
<h2>Question 3</h2>
<ul>
<li class="fragment"><p>We are testing the effects of a new drug on mice</p></li>
<li class="fragment"><p>You have 100 🐁. And three groups: control, dose 1 and dose 2</p></li>
<li class="fragment"><p>You measure their heartbeat pre-trial, 5 weeks post trial, and 10 weeks post trial</p></li>
<li class="fragment"><p>Do we care about individual 🐭 or the general effect of the drug?</p></li>
</ul>
</section>
<section id="question-4" class="slide level2">
<h2>Question 4</h2>

<img data-src="images/clipboard-2338429704.png" class="r-stretch"><ul>
<li class="fragment"><p>Each color represents a different feeding treatment.</p></li>
<li class="fragment"><p>Samples are taken daily</p></li>
</ul>
</section>
<section id="experiments" class="slide level2 scrollable">
<h2>Experiments</h2>
<ol type="1">
<li class="fragment">Fish and Hg. <strong>Research question</strong>: Should we limit consumption of fish over a certain size</li>
<li class="fragment">Infection prevalence in turkeys: <strong>Research question</strong>: You are estimating the probability of an individual being infected to be used as a section on a demographic model?</li>
<li class="fragment">Mice. <strong>Research question</strong>:Is the drug affecting the mice heart rate?</li>
<li class="fragment">Salmon: Does energy availability (food), affects the activity of the ATPase enzime?</li>
</ol>
</section>
<section id="experiments-1" class="slide level2">
<h2>Experiments : 🎣 🦃 🐁🐟</h2>
<p>For each experiment answer:</p>
<ul>
<li class="fragment"><p>How would you analyze the data</p></li>
<li class="fragment"><p>Are they breaking any assumptions?</p></li>
<li class="fragment"><p>What is the individual unit, and what is the experimental unit</p></li>
<li class="fragment"><p>What is the response variable</p></li>
<li class="fragment"><p>Where is the variance coming from?</p></li>
</ul>
</section>
<section id="example-1" class="slide level2">
<h2>Example 1:</h2>
<p>In the first example, we are looking at the relationship between size and Hg concentration, in order to know whether to publish a consumption advisory for fish over a certain size. So, far, we have looked at examples in which our sampling is “random”</p>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code>      size        Hg ind
1 39.14453 1.2254887   1
2 25.90352 1.0468306   2
3 28.82438 0.9466897   3
4 46.96808 1.3566584   4
5 43.08161 1.2574994   5
6 27.06109 1.0369385   6</code></pre>
</div>
</div>
<ul>
<li class="fragment"><p>Could we simply look at it as</p></li>
<li class="fragment"><p><span class="math display">\[
Hg_i \sim \beta_0 + \beta_1 + \epsilon
\]</span></p></li>
</ul>
</section>
<section id="example-1-1" class="slide level2">
<h2>Example 1:</h2>
<p>But now the data looks like this:</p>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code>       size        Hg region ind
1  39.14453 1.2254887      A   1
2  25.90352 1.0468306      A   2
3  28.82438 0.9466897      A   3
25 50.88730 1.3002303      A  25
26 48.88095 1.1308943      B  26
27 59.01028 1.2860683      B  27
56 27.45475 0.5003289      C  56
57 27.77934 0.5540472      C  57
80 29.66874 0.7792851      D  80
81 33.54252 0.7971616      D  81</code></pre>
</div>
</div>
<p>How do we analyze it?</p>
</section>
<section id="so-far-we-have-looked-at-linear-models-or-glms" class="slide level2">
<h2>So far we have looked at linear models (or glms)</h2>
<ul>
<li class="fragment"><p><span class="math display">\[
\underbrace{E[y_i]}_{\text{expected value}} = \underbrace{\beta_0 + \beta_1x_{1,i} + ... \beta_mx_{m,i}}_{deterministic}
\]</span></p></li>
<li class="fragment"><p><span class="math display">\[
y_i \sim \underbrace{N(mean=E[y_i], var=\sigma^2)}_{stochastic}
\]</span></p></li>
<li class="fragment"><p>Same as:</p></li>
<li class="fragment"><p><span class="math display">\[
y_i = \underbrace{\beta_0 + \beta_1x_{1,i} + ... \beta_mx_{m,i}}_{deterministic} \ + \underbrace{\epsilon}_{stachastic}
\]</span></p></li>
<li class="fragment"><p><span class="math display">\[\epsilon \sim nomral(0,\sigma) \]</span></p></li>
</ul>
</section>
<section id="linear-model" class="slide level2">
<h2>linear model</h2>

<img data-src="pres-glm2_files/figure-revealjs/unnamed-chunk-28-1.png" width="960" class="r-stretch"><p><span class="math display">\[ \underbrace{E[y_i]}_{\text{expected value}} = \underbrace{\beta_0 + \beta_1x_{1,i} + ... \beta_mx_{m,i}}_{deterministic} \]</span></p>
<p><span class="math display">\[ y_i \sim \underbrace{N(mean=E[y_i], var=\sigma^2)}_{stochastic} \]</span></p>
</section>
<section id="do-an-equation-in-which-we-introduce-the-effects-of-net" class="slide level2">
<h2>Do an equation in which we introduce the effects of net</h2>
</section>
<section id="mixed-model" class="slide level2">
<h2>Mixed model</h2>
<p>In a mixed model we <strong>introduce</strong> stochastic effects to the “deterministic component”.</p>
<p>In this case:</p>
<ul>
<li class="fragment"><p><span class="math display">\[
\underbrace{E[y_i]}_{\text{expected value}} = \underbrace{\beta_0 + \beta_1x_{1,i} + ... beta_mx_{m,i}}_{deterministic}
\]</span></p></li>
<li class="fragment"><p><span class="math display">\[
y_i \sim \underbrace{N(mean=E[y_i], var=\sigma^2)}_{stochastic}
\]</span></p></li>
<li class="fragment"><p>Same as:</p></li>
<li class="fragment"><p><span class="math display">\[
y_i \sim \underbrace{\beta_0 + \beta_1x_{1,i} + ... \beta_mx_{m,i}}_{deterministic} \ + \underbrace{\epsilon}_{stachastic}
\]</span></p></li>
<li class="fragment"><p>They all are deterministic (are a single value!)</p></li>
</ul>
</section>
<section id="mixed-model-1" class="slide level2">
<h2>Mixed model</h2>
<p>When we talk about the stochastic portion of a model:</p>
<ul>
<li class="fragment"><span class="math display">\[
y_i \sim \underbrace{\beta_0 + \beta_1x_{1,i} + ... \beta_mx_{m,i}}_{deterministic} \ + \underbrace{\epsilon}_{stachastic}
\]</span></li>
<li class="fragment">What is introducing the variance?</li>
<li class="fragment">Is the variance (or observation error) independent?</li>
<li class="fragment">In a mixed model, what is introducing the variance?</li>
<li class="fragment">🎣 🦃 🐁🐟</li>
</ul>
</section>
<section id="mixed-model-2" class="slide level2">
<h2>Mixed model</h2>
<p>Think… how do we introduce that variance?</p>
<p><span class="math display">\[
y_i \sim \underbrace{\beta_0 + \beta_1x_{1,i} + ... \beta_mx_{m,i}}_{deterministic} \ + \underbrace{\epsilon}_{stachastic}
\]</span></p>
<ul>
<li class="fragment"><p>Think for a moment on this specific question: 🐟</p></li>
<li class="fragment"><p><span class="math display">\[
y_i \sim \underbrace{\beta_0 + \beta_1x_{1,i}}_{deterministic} + \underbrace{\epsilon}_{stachastic}
\]</span></p></li>
<li class="fragment"><p><span class="math display">\[
Hg_i \sim \underbrace{\beta_0 + \beta_1size_{i}}_{deterministic} + \underbrace{\epsilon}_{stachastic}
\]</span></p></li>
<li class="fragment"><p><span class="math display">\[ \epsilon \sim N(0,\sigma)\]</span></p></li>
</ul>

<img data-src="pres-glm2_files/figure-revealjs/unnamed-chunk-29-1.png" width="960" class="r-stretch"></section>
<section id="the-variance-can-affect-the-slope-the-intercept-or-both" class="slide level2">
<h2>The variance can affect the slope, the intercept, or both</h2>
<div class="columns">
<div class="column" style="width:60%;">
<div class="cell">
<div class="cell-output-display">
<div>
<figure>
<p><img data-src="pres-glm2_files/figure-revealjs/unnamed-chunk-30-1.png" width="960"></p>
</figure>
</div>
</div>
</div>
</div><div class="column" style="width:40%;">
<p>What is the problem with this? We can actually do a linear model</p>
<ul>
<li class="fragment"><strong>But remember!</strong> there might be some effect of the locations where nets were placed</li>
</ul>
</div></div>
</section>
<section id="plotting-the-data-as-a-linear-model" class="slide level2">
<h2>Plotting the data as a linear model</h2>
<div class="cell">
<div class="cell-output-display">
<div>
<figure>
<p><img data-src="pres-glm2_files/figure-revealjs/unnamed-chunk-31-1.png" width="960"></p>
</figure>
</div>
</div>
</div>
<ul>
<li class="fragment">You might think this is all good… but</li>
</ul>
<div class="cell">
<div class="cell-output-display">
<div>
<figure>
<p><img data-src="pres-glm2_files/figure-revealjs/unnamed-chunk-32-1.png" width="960"></p>
</figure>
</div>
</div>
</div>
<ul>
<li class="fragment"><p>So… we do a <strong>mixed model!</strong> Where we introduce the variance from the site</p></li>
<li class="fragment"><p>But… why don’t we simply add site as a covariate?</p></li>
<li class="fragment"><p>You will be tasked with answering this on your next assignment!</p></li>
</ul>
</section>
<section id="the-variance-can-affect-the-slope-the-intercept-or-both-1" class="slide level2">
<h2>The variance can affect the slope, the intercept, or both</h2>
<ul>
<li class="fragment"><p>Random effects introduce variance.</p></li>
<li class="fragment"><p>It can introduce varianceto the intercept or to the slope</p></li>
</ul>

<img data-src="pres-glm2_files/figure-revealjs/unnamed-chunk-33-1.png" width="960" class="r-stretch"></section>
<section id="mixed-model-3" class="slide level2">
<h2>Mixed model</h2>
<ul>
<li class="fragment"><p><span class="math display">\[
Hg_i \sim \beta_0 + \beta_1size_{i} + \epsilon
\]</span></p></li>
<li class="fragment"><p>i individuals, j sites (4)</p></li>
<li class="fragment"><p><span class="math display">\[
Hg_i \sim \underbrace{(\beta_0 +\underbrace{\gamma_j}_{\text{Random intercept}})}_{intercept} + \underbrace{\beta_1size_{i}}_{slope} +\underbrace{\epsilon}_\text{ind var}
\]</span></p></li>
<li class="fragment"><p>Variance comes from random “selection” of fish within a net</p></li>
<li class="fragment"><p>Variance comes from random “selection” of sites</p></li>
</ul>
</section>
<section id="mixed-model-4" class="slide level2">
<h2>Mixed model</h2>
<p>This is the result of a mixed model:</p>

<img data-src="pres-glm2_files/figure-revealjs/unnamed-chunk-34-1.png" width="960" class="r-stretch"></section>
<section id="mixed-effects-model-output" class="slide level2">
<h2>Mixed effects model output</h2>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code> Family: gaussian  ( identity )
Formula:          Hg ~ size + (1 | region)
Data: HgDat_df

     AIC      BIC   logLik deviance df.resid 
  -176.1   -166.2     92.1   -184.1       84 

Random effects:

Conditional model:
 Groups   Name        Variance Std.Dev.
 region   (Intercept) 0.018240 0.13505 
 Residual             0.005965 0.07724 
Number of obs: 88, groups:  region, 4

Dispersion estimate for gaussian family (sigma^2): 0.00597 

Conditional model:
             Estimate Std. Error z value Pr(&gt;|z|)    
(Intercept) 0.2541317  0.0750840   3.385 0.000713 ***
size        0.0183709  0.0008141  22.565  &lt; 2e-16 ***
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1</code></pre>
</div>
</div>

<img data-src="pres-glm2_files/figure-revealjs/unnamed-chunk-36-1.png" width="960" class="r-stretch"></section>
<section id="output" class="slide level2">
<h2>Output</h2>


<img data-src="pres-glm2_files/figure-revealjs/unnamed-chunk-37-1.png" width="960" class="r-stretch"></section>
    </div>
  <div class="quarto-auto-generated-content" style="display: none;">
<div class="footer footer-default">

</div>
</div></div>

  <script>window.backupDefine = window.define; window.define = undefined;</script>
  <script src="pres glm2_files/libs/revealjs/dist/reveal.js"></script>
  <!-- reveal.js plugins -->
  <script src="pres glm2_files/libs/revealjs/plugin/quarto-line-highlight/line-highlight.js"></script>
  <script src="pres glm2_files/libs/revealjs/plugin/pdf-export/pdfexport.js"></script>
  <script src="pres glm2_files/libs/revealjs/plugin/reveal-menu/menu.js"></script>
  <script src="pres glm2_files/libs/revealjs/plugin/reveal-menu/quarto-menu.js"></script>
  <script src="pres glm2_files/libs/revealjs/plugin/reveal-chalkboard/plugin.js"></script>
  <script src="pres glm2_files/libs/revealjs/plugin/quarto-support/support.js"></script>
  

  <script src="pres glm2_files/libs/revealjs/plugin/notes/notes.js"></script>
  <script src="pres glm2_files/libs/revealjs/plugin/search/search.js"></script>
  <script src="pres glm2_files/libs/revealjs/plugin/zoom/zoom.js"></script>
  <script src="pres glm2_files/libs/revealjs/plugin/math/math.js"></script>
  <script>window.define = window.backupDefine; window.backupDefine = undefined;</script>

  <script>

      // Full list of configuration options available at:
      // https://revealjs.com/config/
      Reveal.initialize({
'controlsAuto': true,
'previewLinksAuto': false,
'pdfSeparateFragments': false,
'autoAnimateEasing': "ease",
'autoAnimateDuration': 1,
'autoAnimateUnmatched': true,
'jumpToSlide': true,
'menu': {"side":"left","useTextContentForMissingTitles":true,"markers":false,"loadIcons":false,"custom":[{"title":"Tools","icon":"<i class=\"fas fa-gear\"></i>","content":"<ul class=\"slide-menu-items\">\n<li class=\"slide-tool-item active\" data-item=\"0\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.fullscreen(event)\"><kbd>f</kbd> Fullscreen</a></li>\n<li class=\"slide-tool-item\" data-item=\"1\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.speakerMode(event)\"><kbd>s</kbd> Speaker View</a></li>\n<li class=\"slide-tool-item\" data-item=\"2\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.overview(event)\"><kbd>o</kbd> Slide Overview</a></li>\n<li class=\"slide-tool-item\" data-item=\"3\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.togglePdfExport(event)\"><kbd>e</kbd> PDF Export Mode</a></li>\n<li class=\"slide-tool-item\" data-item=\"4\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.toggleScrollView(event)\"><kbd>r</kbd> Scroll View Mode</a></li>\n<li class=\"slide-tool-item\" data-item=\"5\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.toggleChalkboard(event)\"><kbd>b</kbd> Toggle Chalkboard</a></li>\n<li class=\"slide-tool-item\" data-item=\"6\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.toggleNotesCanvas(event)\"><kbd>c</kbd> Toggle Notes Canvas</a></li>\n<li class=\"slide-tool-item\" data-item=\"7\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.downloadDrawings(event)\"><kbd>d</kbd> Download Drawings</a></li>\n<li class=\"slide-tool-item\" data-item=\"8\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.keyboardHelp(event)\"><kbd>?</kbd> Keyboard Help</a></li>\n</ul>"}],"openButton":true},
'chalkboard': {"buttons":true},
'smaller': false,
 
        // Display controls in the bottom right corner
        controls: false,

        // Help the user learn the controls by providing hints, for example by
        // bouncing the down arrow when they first encounter a vertical slide
        controlsTutorial: false,

        // Determines where controls appear, "edges" or "bottom-right"
        controlsLayout: 'edges',

        // Visibility rule for backwards navigation arrows; "faded", "hidden"
        // or "visible"
        controlsBackArrows: 'faded',

        // Display a presentation progress bar
        progress: true,

        // Display the page number of the current slide
        slideNumber: false,

        // 'all', 'print', or 'speaker'
        showSlideNumber: 'all',

        // Add the current slide number to the URL hash so that reloading the
        // page/copying the URL will return you to the same slide
        hash: true,

        // Start with 1 for the hash rather than 0
        hashOneBasedIndex: false,

        // Flags if we should monitor the hash and change slides accordingly
        respondToHashChanges: true,

        // Push each slide change to the browser history
        history: true,

        // Enable keyboard shortcuts for navigation
        keyboard: true,

        // Enable the slide overview mode
        overview: true,

        // Disables the default reveal.js slide layout (scaling and centering)
        // so that you can use custom CSS layout
        disableLayout: false,

        // Vertical centering of slides
        center: false,

        // Enables touch navigation on devices with touch input
        touch: true,

        // Loop the presentation
        loop: false,

        // Change the presentation direction to be RTL
        rtl: false,

        // see https://revealjs.com/vertical-slides/#navigation-mode
        navigationMode: 'linear',

        // Randomizes the order of slides each time the presentation loads
        shuffle: false,

        // Turns fragments on and off globally
        fragments: true,

        // Flags whether to include the current fragment in the URL,
        // so that reloading brings you to the same fragment position
        fragmentInURL: false,

        // Flags if the presentation is running in an embedded mode,
        // i.e. contained within a limited portion of the screen
        embedded: false,

        // Flags if we should show a help overlay when the questionmark
        // key is pressed
        help: true,

        // Flags if it should be possible to pause the presentation (blackout)
        pause: true,

        // Flags if speaker notes should be visible to all viewers
        showNotes: false,

        // Global override for autoplaying embedded media (null/true/false)
        autoPlayMedia: null,

        // Global override for preloading lazy-loaded iframes (null/true/false)
        preloadIframes: null,

        // Number of milliseconds between automatically proceeding to the
        // next slide, disabled when set to 0, this value can be overwritten
        // by using a data-autoslide attribute on your slides
        autoSlide: 0,

        // Stop auto-sliding after user input
        autoSlideStoppable: true,

        // Use this method for navigation when auto-sliding
        autoSlideMethod: null,

        // Specify the average time in seconds that you think you will spend
        // presenting each slide. This is used to show a pacing timer in the
        // speaker view
        defaultTiming: null,

        // Enable slide navigation via mouse wheel
        mouseWheel: false,

        // The display mode that will be used to show slides
        display: 'block',

        // Hide cursor if inactive
        hideInactiveCursor: true,

        // Time before the cursor is hidden (in ms)
        hideCursorTime: 5000,

        // Opens links in an iframe preview overlay
        previewLinks: false,

        // Transition style (none/fade/slide/convex/concave/zoom)
        transition: 'none',

        // Transition speed (default/fast/slow)
        transitionSpeed: 'default',

        // Transition style for full page slide backgrounds
        // (none/fade/slide/convex/concave/zoom)
        backgroundTransition: 'none',

        // Number of slides away from the current that are visible
        viewDistance: 3,

        // Number of slides away from the current that are visible on mobile
        // devices. It is advisable to set this to a lower number than
        // viewDistance in order to save resources.
        mobileViewDistance: 2,

        // The "normal" size of the presentation, aspect ratio will be preserved
        // when the presentation is scaled to fit different resolutions. Can be
        // specified using percentage units.
        width: 1050,

        height: 700,

        // Factor of the display size that should remain empty around the content
        margin: 0.1,

        math: {
          mathjax: 'https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.9/MathJax.js',
          config: 'TeX-AMS_HTML-full',
          tex2jax: {
            inlineMath: [['\\(','\\)']],
            displayMath: [['\\[','\\]']],
            balanceBraces: true,
            processEscapes: false,
            processRefs: true,
            processEnvironments: true,
            preview: 'TeX',
            skipTags: ['script','noscript','style','textarea','pre','code'],
            ignoreClass: 'tex2jax_ignore',
            processClass: 'tex2jax_process'
          },
        },

        // reveal.js plugins
        plugins: [QuartoLineHighlight, PdfExport, RevealMenu, RevealChalkboard, QuartoSupport,

          RevealMath,
          RevealNotes,
          RevealSearch,
          RevealZoom
        ]
      });
    </script>
    

    <script>

      // htmlwidgets need to know to resize themselves when slides are shown/hidden.

      // Fire the "slideenter" event (handled by htmlwidgets.js) when the current

      // slide changes (different for each slide format).

      (function () {

        // dispatch for htmlwidgets

        function fireSlideEnter() {

          const event = window.document.createEvent("Event");

          event.initEvent("slideenter", true, true);

          window.document.dispatchEvent(event);

        }

    

        function fireSlideChanged(previousSlide, currentSlide) {

          fireSlideEnter();

    

          // dispatch for shiny

          if (window.jQuery) {

            if (previousSlide) {

              window.jQuery(previousSlide).trigger("hidden");

            }

            if (currentSlide) {

              window.jQuery(currentSlide).trigger("shown");

            }

          }

        }

    

        // hookup for slidy

        if (window.w3c_slidy) {

          window.w3c_slidy.add_observer(function (slide_num) {

            // slide_num starts at position 1

            fireSlideChanged(null, w3c_slidy.slides[slide_num - 1]);

          });

        }

    

      })();

    </script>

    

    <script id="quarto-html-after-body" type="application/javascript">
    window.document.addEventListener("DOMContentLoaded", function (event) {
      const toggleBodyColorMode = (bsSheetEl) => {
        const mode = bsSheetEl.getAttribute("data-mode");
        const bodyEl = window.document.querySelector("body");
        if (mode === "dark") {
          bodyEl.classList.add("quarto-dark");
          bodyEl.classList.remove("quarto-light");
        } else {
          bodyEl.classList.add("quarto-light");
          bodyEl.classList.remove("quarto-dark");
        }
      }
      const toggleBodyColorPrimary = () => {
        const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
        if (bsSheetEl) {
          toggleBodyColorMode(bsSheetEl);
        }
      }
      toggleBodyColorPrimary();  
      const tabsets =  window.document.querySelectorAll(".panel-tabset-tabby")
      tabsets.forEach(function(tabset) {
        const tabby = new Tabby('#' + tabset.id);
      });
      const isCodeAnnotation = (el) => {
        for (const clz of el.classList) {
          if (clz.startsWith('code-annotation-')) {                     
            return true;
          }
        }
        return false;
      }
      const onCopySuccess = function(e) {
        // button target
        const button = e.trigger;
        // don't keep focus
        button.blur();
        // flash "checked"
        button.classList.add('code-copy-button-checked');
        var currentTitle = button.getAttribute("title");
        button.setAttribute("title", "Copied!");
        let tooltip;
        if (window.bootstrap) {
          button.setAttribute("data-bs-toggle", "tooltip");
          button.setAttribute("data-bs-placement", "left");
          button.setAttribute("data-bs-title", "Copied!");
          tooltip = new bootstrap.Tooltip(button, 
            { trigger: "manual", 
              customClass: "code-copy-button-tooltip",
              offset: [0, -8]});
          tooltip.show();    
        }
        setTimeout(function() {
          if (tooltip) {
            tooltip.hide();
            button.removeAttribute("data-bs-title");
            button.removeAttribute("data-bs-toggle");
            button.removeAttribute("data-bs-placement");
          }
          button.setAttribute("title", currentTitle);
          button.classList.remove('code-copy-button-checked');
        }, 1000);
        // clear code selection
        e.clearSelection();
      }
      const getTextToCopy = function(trigger) {
          const codeEl = trigger.previousElementSibling.cloneNode(true);
          for (const childEl of codeEl.children) {
            if (isCodeAnnotation(childEl)) {
              childEl.remove();
            }
          }
          return codeEl.innerText;
      }
      const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
        text: getTextToCopy
      });
      clipboard.on('success', onCopySuccess);
      if (window.document.getElementById('quarto-embedded-source-code-modal')) {
        const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
          text: getTextToCopy,
          container: window.document.getElementById('quarto-embedded-source-code-modal')
        });
        clipboardModal.on('success', onCopySuccess);
      }
        var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
        var mailtoRegex = new RegExp(/^mailto:/);
          var filterRegex = new RegExp('/' + window.location.host + '/');
        var isInternal = (href) => {
            return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
        }
        // Inspect non-navigation links and adorn them if external
     	var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
        for (var i=0; i<links.length; i++) {
          const link = links[i];
          if (!isInternal(link.href)) {
            // undo the damage that might have been done by quarto-nav.js in the case of
            // links that we want to consider external
            if (link.dataset.originalHref !== undefined) {
              link.href = link.dataset.originalHref;
            }
          }
        }
      function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
        const config = {
          allowHTML: true,
          maxWidth: 500,
          delay: 100,
          arrow: false,
          appendTo: function(el) {
              return el.closest('section.slide') || el.parentElement;
          },
          interactive: true,
          interactiveBorder: 10,
          theme: 'light-border',
          placement: 'bottom-start',
        };
        if (contentFn) {
          config.content = contentFn;
        }
        if (onTriggerFn) {
          config.onTrigger = onTriggerFn;
        }
        if (onUntriggerFn) {
          config.onUntrigger = onUntriggerFn;
        }
          config['offset'] = [0,0];
          config['maxWidth'] = 700;
        window.tippy(el, config); 
      }
      const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
      for (var i=0; i<noterefs.length; i++) {
        const ref = noterefs[i];
        tippyHover(ref, function() {
          // use id or data attribute instead here
          let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
          try { href = new URL(href).hash; } catch {}
          const id = href.replace(/^#\/?/, "");
          const note = window.document.getElementById(id);
          if (note) {
            return note.innerHTML;
          } else {
            return "";
          }
        });
      }
      const findCites = (el) => {
        const parentEl = el.parentElement;
        if (parentEl) {
          const cites = parentEl.dataset.cites;
          if (cites) {
            return {
              el,
              cites: cites.split(' ')
            };
          } else {
            return findCites(el.parentElement)
          }
        } else {
          return undefined;
        }
      };
      var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
      for (var i=0; i<bibliorefs.length; i++) {
        const ref = bibliorefs[i];
        const citeInfo = findCites(ref);
        if (citeInfo) {
          tippyHover(citeInfo.el, function() {
            var popup = window.document.createElement('div');
            citeInfo.cites.forEach(function(cite) {
              var citeDiv = window.document.createElement('div');
              citeDiv.classList.add('hanging-indent');
              citeDiv.classList.add('csl-entry');
              var biblioDiv = window.document.getElementById('ref-' + cite);
              if (biblioDiv) {
                citeDiv.innerHTML = biblioDiv.innerHTML;
              }
              popup.appendChild(citeDiv);
            });
            return popup.innerHTML;
          });
        }
      }
    });
    </script>
    

</body></html>